### ISSUE TITLE
-itol parameter

### ISSUE THREAD

**Issue by VladimirRoudko** [bzhanglab/PepQuery#10]
Hello,

I am new to the proteomics and would like to use pepquery to different MS datasets.  In the list of standalone pepquery parameters, "-itol" seems to be machine-dependent.  Which value should I provide for each MS machine currently available on the market? 

Thank you

**Comment by wenbostar** [comment]
This really depends on both the MS machine and the model setting for data generation. It means even for the same machine, different settings can give you different mass accuracy. There are a lot of different MS instruments in the market. If you can provide a list that you're interested in, I will probably be able to tell you the general setting of "-itol” for them.

**Comment by VladimirRoudko** [comment]
Thank you! Though I realized, I need to know about two parameters: -tol (in ppm) for first MS spectra and -itol (in Da) for second MS spectra. Here are the instruments I might be interested:

Thermo Orbitrap Fusion Lumos Tribrid
Thermo LTQ Orbitrap Velos ion trap
Thermo Q Exactive

Thank you!

**Comment by wenbostar** [comment]
> Thermo Orbitrap Fusion Lumos Tribrid

Orbitrap (MS1) - Orbitrap (MS2): tol = 10ppm, itol = 0.05 Da
Orbitrap (MS1) - ion trap (MS2): tol = 10ppm, itol = 0.6 Da

> Thermo LTQ Orbitrap Velos ion trap

Orbitrap (MS1) - ion trap (MS2): tol = 10ppm, itol = 0.6 Da

> Thermo Q Exactive

tol = 10ppm, itol = 0.05 Da

**Comment by VladimirRoudko** [comment]
Thanks a lot, that's really great.  Just in case, do you have any reading to suggest, to learn more about MS/MS analysis in general? Not too general, but with technical details?  

Thank you!

**Comment by wenbostar** [comment]
You're welcome. You can find a very nice tutorial here about bioinformatics for proteomics: [https://www.compomics.be/bioinformatics-for-proteomics/](https://www.compomics.be/bioinformatics-for-proteomics/).

**Comment by VladimirRoudko** [comment]
Thank you, that's great!

Vladimir

**Comment by VladimirRoudko** [comment]
Hello,

My apologies for re-opening this thread. I noticed if I change the -itol parameter and perform search using the same dataset, I get different output.  

I understand, that -itol parameter has something to do with MS-machine configuration and experiment setup, but still: how to be confident that the results of the pepquery search are not affected by this parameter? Especially, in the cases when -itol cannot be inferred correctly.

Thanks,
Vladimir

**Comment by wenbostar** [comment]
Hi Vladimir,

The parameter `-itol ` is similar with `-tol` which is determined by the MS instrument.  You have to set the value correctly for this parameter based on the MS instrument which is used to generate the MS/MS data. This parameter controls the mass tolerance windows when doing fragment ion matching thus it can affect the peptide spectrum scoring.
