### ISSUE TITLE
"total_db" and "charge" output parameter

### ISSUE THREAD

**Issue by VladimirRoudko** [bzhanglab/PepQuery#11]
Hello,

what is exact utility of "total_db" output parameter?  If my predicted PSM has "n_db" = 0 (which means, that this spectrum ddi not find anything in reference db as a better match defined by score), so then why do I have non-zero values in "total_db"?  Should I worry about high (>100) numbers in this field?

Also, if predicted "charge" of the peptide is higher then 3 - is it devaluates my PSM hit or not?

Thank you!
Vladimir

**Comment by wenbostar** [comment]
Hi Vladimir,

> what is exact utility of "total_db" output parameter? If my predicted PSM has "n_db" = 0 (which means, that this spectrum ddi not find anything in reference db as a better match defined by score), so then why do I have non-zero values in "total_db"? Should I worry about high (>100) numbers in this field?

You can find a description of each column in the output psm_rank.txt file here: http://pepquery.org/document.html#saoutput. Specifically, "total_db" is the total number of matched peptides from the reference protein database based on precursor mass for a spectrum without regarding matching score. You don't need to worry about if you get a high number (>100) in this field. That just means there are a lot of peptides from the reference database that can be matched to the spectrum simply based on precursor mass. 

> Also, if predicted "charge" of the peptide is higher then 3 - is it devaluates my PSM hit or not?

The charge information for a spectrum in the output file is not predicted by PepQuery. It's directly from your input MGF file. In some cases that precursor charge information is not available for a spectrum in the input MGF file, PepQuery will consider 2+ and 3+ for this spectrum in default and finally pick up the one with higher score.

Bo

**Comment by VladimirRoudko** [comment]
Thank you!
