### ISSUE TITLE
What corresponds to web-server "Target event" in stand-alone version

### ISSUE THREAD

**Issue by VladimirRoudko** [bzhanglab/PepQuery#12]
Hello,

just stumbled over the difference between web-server and standalone version results. Seems, that web-server "target event" is not clearly defined in stand-alone version.  What would be the parameters look like for st-alone pepquery, if I want to use whole protein sequence to search for peptide PSMs?

Thanks

**Comment by VladimirRoudko** [comment]
Just FYI:
let's say, how should I modify my command line:
pepquery -o "pep" -prefix "pep" -t 1 -ms "${fn}" -pep "$PEPTIDE" -db "$PDB" -n 1000 -m 1 -maxLength 50 -minLength 7 -um -hc FALSE -cpu 10

if the -pep "$PEPTIDE" has a file "$PEPTIDE" which stores protein sequences, not the peptide ones.

**Comment by wenbostar** [comment]
> just stumbled over the difference between web-server and standalone version results. Seems, that web-server "target event" is not clearly defined in stand-alone version. What would be the parameters look like for st-alone pepquery, if I want to use whole protein sequence to search for peptide PSMs?

"Target event" corresponds to "-t" option in the standalone version. If your input is a protein sequence, then you need to set both -i and -t like this: -i input_protein_sequence -t 1.

**Comment by VladimirRoudko** [comment]
and should I drop the "-pep" parameter then?

**Comment by wenbostar** [comment]
> let's say, how should I modify my command line:
pepquery -o "pep" -prefix "pep" -t 1 -ms "${fn}" -pep "$PEPTIDE" -db "$PDB" -n 1000 -m 1 -maxLength 50 -minLength 7 -um -hc FALSE -cpu 10
if the -pep "$PEPTIDE" has a file "$PEPTIDE" which stores protein sequences, not the peptide ones.

In this case, please remove -pep and use -t:  -i $PEPTIDE -t 1.

**Comment by VladimirRoudko** [comment]
great, thank you!
