### ISSUE TITLE
HyperScore threshold

### ISSUE THREAD

**Issue by VladimirRoudko** [bzhanglab/PepQuery#15]
Hello,

Is it valuable to apply hyper score threshold to filter the most significant PSM spectra? 

Let's say, I get ~3000 PSMs with p-value < 0.01. Will it be useful to stringen selection with hyper score threshold? If yes, which one to apply?

**Comment by wenbostar** [comment]
If you use the latest version of PepQuery, in default the minimum score is 12 for hyper score. It means the PSMs with hyperscore <= 12 are filtered out. This is the cutoff we recommend.

**Comment by wenbostar** [comment]
Did you set parameter -um?

**Comment by VladimirRoudko** [comment]
Yes, I did. Indeed, the minimum score is 12 in my output.  Is there any reason to increase this threshold?

**Comment by wenbostar** [comment]
The cutoff of 12 is a good balance between sensitivity and specificity. Users don't need to increase it in most of the cases. You can load the identification results of PepQuery into [PDV](https://github.com/wenbostar/PDV) to check the quality by looking at the annotated spectra. By the way, did you use both p-value (p-value <= 0.01) and n_ptm (n_ptm == 0) to filter the identification result?

**Comment by VladimirRoudko** [comment]
I always used only p-value <= 0.01.  N_ptm widely varies: from -1 to >100. Should I filter output using both parameters: p-value and n_ptm?  How will n_ptm improve my output, if p-value is already < 0.01?

**Comment by wenbostar** [comment]
When you set -um, it will perform competitive filtering based on unrestricted modification searching (step 5 described in [the paper of PepQuery](https://genome.cshlp.org/content/29/3/485.full)). The column "**n_ptm**" is related to this validation. In PepQuery, if the p-value for a PSM is <= 0.01, this PSM will be further validated using the competitive filtering based on unrestricted modification searching. As described in the paper, we consider more than 1000 modifications in this validation and it has been shown to be very effective to remove false identifications. We recommend you to use both pvalue <= 0.01 and n_ptm ==0 (n_ptm: the number of better matched modification peptides (reference/known peptides) when performing the unrestricted modification searching) to filter the identification results.  You can find an explanation of n_ptm in this issues: #5.

**Comment by VladimirRoudko** [comment]
Thank you very much, that's very helpful! Sorry for replicating the question with n_ptm="-1". It clarifies everything now.  
Just small remark: what's your opinion, is it necessary to do p-value adjustment when running multiple identifications or not?

Thank you!

**Comment by VladimirRoudko** [comment]
Actually, I was just reading issue #5 , and got a bit confused:

 if my p-value <= 0.01 AND n_ptm = "-1" - is this hit confident or not?

Thank you again

**Comment by wenbostar** [comment]
> Just small remark: what's your opinion, is it necessary to do p-value adjustment when running multiple identifications or not?

It might be useful. But I don't have a good way to do this.

**Comment by wenbostar** [comment]
> Actually, I was just reading issue #5 , and got a bit confused:
if my p-value <= 0.01 AND n_ptm = "-1" - is this hit confident or not?

It's impossible to have cases like this. If the p-value of a PSM is > 0.01, it will not perform competitive filtering based on unrestricted modification searching and n_ptm will be -1. If the p-value of a PSM is <= 0.01, it will perform competitive filtering based on unrestricted modification searching and n_ptm will be >= 0.

**Comment by VladimirRoudko** [comment]
Thank you!
