### ISSUE TITLE
conflicting output

### ISSUE THREAD

**Issue by VladimirRoudko** [bzhanglab/PepQuery#16]
Hello Bo,

I have stumbled over one observation, which makes it difficult the output interpretation. I run pepquery search with enabled "-um -hc FALSE" options. Then I check my output for certain peptide, let's say "MPPSGSQAPPGSQSIMMSWMPPLAPCAACPCSPAPTLCPAHPAR", and I get in the sample A: score = "12.2598876", p-value="0.002997" and n_ptm="16", while in the sample B: score = "13.8024207", p-value = "9.99E-04" and n_ptm="0". Eyeballing the MS/MS spectra suggests that both results are highly similar. However, based on the output, I should drop the peptide based on the sample A, and retain it based on the sample B. So, my question is: this peptide - false or true positive?

Also, second observation: I am getting multiple results with n_db=0, p_value < 0.01 and n_ptm="-1".  Could you help me to understand, what these hits mean?

Thank you,
Vladimir

**Comment by wenbostar** [comment]
> I have stumbled over one observation, which makes it difficult the output interpretation. I run pepquery search with enabled "-um -hc FALSE" options. Then I check my output for certain peptide, let's say "MPPSGSQAPPGSQSIMMSWMPPLAPCAACPCSPAPTLCPAHPAR", and I get in the sample A: score = "12.2598876", p-value="0.002997" and n_ptm="16", while in the sample B: score = "13.8024207", p-value = "9.99E-04" and n_ptm="0". Eyeballing the MS/MS spectra suggests that both results are highly similar. However, based on the output, I should drop the peptide based on the sample A, and retain it based on the sample B. So, my question is: this peptide - false or true positive?

Can you share the identification results (the whole output folders) to me? I can take a look.

>Also, second observation: I am getting multiple results with n_db=0, p_value < 0.01 and n_ptm="-1". Could you help me to understand, what these hits mean?

Can you send me the psm_rank.txt file to me?

Bo

**Comment by VladimirRoudko** [comment]
Sure, could you share with me your email?

**Comment by wenbostar** [comment]
bo.wen AT bcm.edu

**Comment by wenbostar** [comment]
Hi @VladimirRoudko , 

> Also, second observation: I am getting multiple results with n_db=0, p_value < 0.01 and n_ptm="-1". Could you help me to understand, what these hits mean?

Thanks for sharing the result. In the identification result that you sent to me, for all the PSMs with n_db ==0, pvalue <= 0.01 and n_ptm==-1, the "rank" of them are all >=2. This means for these PSMs, multiple input peptides or multiple different forms of the same peptide (different modifications) are mapped to the same spectra. For a spectrum, if there are multiple input peptides or multiple different forms of the same peptide (different modifications, an example is shown below) mapped to it, these matches (PSMs) will be ranked based on their scores and the PSMs with rank >=2 will have n_ptm = -1 (the matches are not confident).

![image](https://user-images.githubusercontent.com/5302110/69101956-a9addc00-0a26-11ea-8002-0e445b3f6ce3.png)



Bo

**Comment by wenbostar** [comment]
> I have stumbled over one observation, which makes it difficult the output interpretation. I run pepquery search with enabled "-um -hc FALSE" options. Then I check my output for certain peptide, let's say "MPPSGSQAPPGSQSIMMSWMPPLAPCAACPCSPAPTLCPAHPAR", and I get in the sample A: score = "12.2598876", p-value="0.002997" and n_ptm="16", while in the sample B: score = "13.8024207", p-value = "9.99E-04" and n_ptm="0". Eyeballing the MS/MS spectra suggests that both results are highly similar. However, based on the output, I should drop the peptide based on the sample A, and retain it based on the sample B. So, my question is: this peptide - false or true positive?

The general interpretation for this result is that the peptide is confident (present) in sample B not in sample A. But for this specific case, both scores are not hight. I recommend you to find extra evidence for this identification.  

Bo

**Comment by VladimirRoudko** [comment]
Hi Bo,

thank you very much for the answers! Its very helpful and clarifies everything.  

Vladimir
