### ISSUE TITLE
PSM validation

### ISSUE THREAD

**Issue by mavino** [bzhanglab/PepQuery#17]
I have some peptides I identify from an MS/MS analysis. I would like to know just the hyperscore and MVH related to its sequence spectrum (which I already have)...is there way to get jut those scores through your stand-alone version? Thank you.

**Comment by wenbostar** [comment]
Could you please explain a little bit more about what you need? Do you want to directly call the scoring functions through the stand-alone version without using other components?

**Comment by mavino** [comment]
this is my command line:
```
java -jar pepquery-1.3.jar -pep NAEQYKDQADK -ms ../../Documents/Roucou/proteogenomic/Exp1_786O_nox_scr.mgf -db ../../Documents/example.fasta -c 1 -cpu 12 -t 1 -itol 0.02 -maxCharge 2 -tol 5 -o ../../Documents -m 1
```
You see I have a peptide NAEQYKDQADK which was identified running peptideshaker on 4 engines and a human protein database. This peptide is coming from a particular spectrum which in a different analysis is giving me another peptide. So from the same spectrum I have two different peptides identified. Now I want to use the scoring algorithms that you have to decide which peptide is better for that particular score.

However, when I run that peptide with that line of code, first I have to give a fake database because the analysis to go on does not have to find it in my database (of course it is a novel identification software), then it detects my peptide in my MS/MS experiments finding exactly the spectrum it is coming from in my analysis. However, of course, if finds also other possible spectra and give me the scores.

My purpose is not finding any possible spectra for my peptide but just score it for the reason that I told you above.
I was wondering if I can use the software just for scoring my peptide.

**Comment by wenbostar** [comment]
PepQuery can definitely help you determine which match is more confident. But we cannot use PepQuery as we usually use it for novel peptide identification for this purpose. I can show you how to do that if you can send me the following information:

1. The particular spectrum in MGF format;
2. The two peptide sequences;
3. The reference database you used for PeptideShaker.

Bo

**Comment by mavino** [comment]
that would be great thanks...
alright I am attaching what you asked...the parameters where set up in SearchGui to call PeptideShaker, so I am attaching you those.
Can I have your email to share with you through OneDrive my database since it is too big to attach it.

Thank you very much.
[peptidesequnce2.txt](https://github.com/bzhanglab/PepQuery/files/3876211/peptidesequnce2.txt)
[peptidesequnce1.txt](https://github.com/bzhanglab/PepQuery/files/3876212/peptidesequnce1.txt)
![Screenshot from 2019-11-21 13-45-49](https://user-images.githubusercontent.com/22825333/69367204-d13eb780-0c65-11ea-87c4-69cdd356a196.png)
[spectrum.txt](https://github.com/bzhanglab/PepQuery/files/3876221/spectrum.txt)

**Comment by wenbostar** [comment]
Can you zip your database (only the target sequences not decoy sequences) and then share it with me directly using github?

**Comment by mavino** [comment]
[RefsProt_2x_1.zip](https://github.com/bzhanglab/PepQuery/files/3876578/RefsProt_2x_1.zip)
here you are...thanks a lot again...

**Comment by wenbostar** [comment]
Below please find the method for validation of PSMs. Specifically, put the two peptides in a file "pep.txt" as shown below.
```shell
○ → cat pep.txt
NAEQYKDQADK
NAMKNLWCEK
```

Then remove the two peptides from your reference database (new database without including the two peptides: RefsProt_2x_1_remove_NAEQYKDQADK_and_NAMKNLWCEK.fasta ). The database file you shared with me is not a standard fasta format. I changed a little bit as shown below.

```shell
>E9PB28|TX=9606 OS=Human ...
MAADTPGKPSASPMAGAPASASRTPDKPRSAAEHRKVGSRPGVRGATGGREGRGTQPVPD
PQSSKPVMEKRRRARINESLAQLKTLILDALRKESSRHSKLEKADILEMTVRHLRSLRRV
QVTAALSADPAVLGKYRAGFHECLAEVNRFLAGCEGVPADVRSRLLGHLAACLRQLGPSR
RPASLSPAAPAEAPAPEVYAGRPLLPSLGGPFPLLAPPLLPGLTRALPAAPRAGPQGPGG
PWRPWLR

changed to
> |E9PB28|TX=9606 OS=Human ...
MAADTPGKPSASPMAGAPASASRTPDKPRSAAEHRKVGSRPGVRGATGGREGRGTQPVPD
PQSSKPVMEKRRRARINESLAQLKTLILDALRKESSRHSKLEKADILEMTVRHLRSLRRV
QVTAALSADPAVLGKYRAGFHECLAEVNRFLAGCEGVPADVRSRLLGHLAACLRQLGPSR
RPASLSPAAPAEAPAPEVYAGRPLLPSLGGPFPLLAPPLLPGLTRALPAAPRAGPQGPGG
PWRPWLR
```

Last, run the command line as shown below. 

```shell
○ → java -jar pepquery-1.3.jar -pep pep.txt  \
      -ms spectrum.mgf  \
      -db RefsProt_2x_1_remove_NAEQYKDQADK_and_NAMKNLWCEK.fasta  \
      -c 1 -cpu 12 -itol 0.02 -tol 5 -o out -m 1 -um
```

After the analysis is finished, you can find the validation result in file: out/psm_rank.txt

![image](https://user-images.githubusercontent.com/5302110/69379511-3a2e2b80-0c76-11ea-8598-60d209a8fb57.png)

The peptide NAEQYKDQADK (score: 37.78618, pvalue: 0.0001010918) has much better match to the spectrum than NAMKNLWCEK (score: 13.55607, pvalue: 0.0110003084). You can also load the identification results (out/psm_rank.txt and out/psm_rank.mgf) into [PDV](https://doi.org/10.1093/bioinformatics/bty770) for visualization as shown below. It's obvious that NAEQYKDQADK has much better match.

![psm_validation](https://user-images.githubusercontent.com/5302110/69378692-837d7b80-0c74-11ea-8bc8-e8a46f754df2.PNG)

**Comment by mavino** [comment]
that is great thanks a lot, the one thing I don't understand is how you remove my peptides from the database, what do you do? You blast them against the database? And if that has to be done why not giving a fake database from the beginning since I have to re run this analysis for many couples of peptides. Let me know what you think?

**Comment by wenbostar** [comment]
In the analysis, I used [pepmap](https://github.com/wenbostar/pepmap) to map the two peptides to your reference database to find exactly matched proteins. Then went to the reference database file to remove the two peptides. If we do like this, then the two peptides are "novel" peptides compared with the new reference protein database. With that, we can use the [standard workflow implemented in PepQuery](https://genome.cshlp.org/content/29/3/485/F2.expansion.html) to validate your PSMs. 

If you only need the "Hyperscore" or "MVH" score for your PSMs, then you can provide an empty reference database file and use the command line below:

```shell
○ → cat test.fasta

○ → java -jar pepquery-1.3.jar -pep pep.txt  \
                 -ms spectrum.mgf  \
                 -db test.fasta -c 1 -cpu 12 -itol 0.02 -tol 5 -o out -m 1  \
                 -n 1
```

**Comment by mavino** [comment]
Great thank you very much...I appreciate.
