### ISSUE TITLE
Index reference protein database and MS/MS data for fast searching

### ISSUE THREAD

**Issue by Seb-Leb** [bzhanglab/PepQuery#18]
Hello, the first step of a search always involves indexing the reference library into a sql db. Is it possible to make this persist for future searches? 
thank you

**Comment by wenbostar** [comment]
The standalone version of PepQuery doesn't index the reference protein database to an SQL db when you're doing a search. Could you please tell me your command line and the output?

Bo

**Comment by Seb-Leb** [comment]
Here is what I am running:
`java -jar /home/group/tools/PepQuery_v1.2.0/pepquery.jar -itol 0.05 -hc TRUE -um -cpu 4 -pep /home/snp_peptides.txt -db /home/custom_ref_lib.fasta -ms home/no_backup/public_data/syn10142580_mgf/mfon_38_02.mgf -o /home/syn10142580_mgf/mfon_38_02`

and the output:
```
...
Random peptide number: 10000
CPU: 4
#############################################
Input peptide sequences:124
Don't find indexed database:/home/custom_ref_lib.fasta.sqldb
Use database:/home/custom_ref_lib.fasta
Load db file: /home/custom_ref_lib.fasta
Start indexing fasta file
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Indexing took 99.996075793 seconds and consumes 248.351536 MB
2019-11-21 12:07:39 [ INFO] Valid target peptides: 124
2019-11-21 12:07:39 [ INFO] Generate peptide objects ...
CPU: 4
2019-11-21 12:07:39 [ INFO] Generate peptide objects done.
Build target peptide index done.
Finished:10000
Finished:20000
...
```

**Comment by wenbostar** [comment]
This step is to search target peptides against the MS/MS data to find candidate spectra for the target peptides. The time for this step really depends on the size of your MS/MS data and the number of target peptides (/home/snp_peptides.txt). It looks you used the default values for parameters -tol, -varMod and -fixMod. Please make sure the default settings really match with your MS/MS data.

**Comment by Seb-Leb** [comment]
OK so custom_ref_lib.fasta.sqldb is not actually generated, the `Start indexing fasta file` is for the target peptides?
Would there be any performance gains if there were an indexed ref fasta library?

**Comment by wenbostar** [comment]
> OK so custom_ref_lib.fasta.sqldb is not actually generated, the Start indexing fasta file is for the target peptides?

This is internal peptide mapping.

> Would there be any performance gains if there were an indexed ref fasta library?

Yes, you can index both reference protein database and MS/MS data before you do the search, then it will be much faster.  You can find how to do that here: [Index reference protein database and MS/MS data for fast searching](http://pepquery.org/document.html#index).

**Comment by Seb-Leb** [comment]
Ok great I will do that!
thank you

**Comment by ada6090** [comment]
Hi 
I am still not sure how to index the reference protein database ? the command seems to work only for MS files

**Comment by wenbostar** [comment]
With PepQuery2, reference protein database indexing is no longer needed.
