### ISSUE TITLE
No permission to download Dataset 1: iPRG-2015 and Procedures for using PepQuery

### ISSUE THREAD

**Issue by cvn001** [bzhanglab/PepQuery#20]
Hi,

I can not download the example dataset (iPRG-2015) for the stand-alone application as well as the procedures (Procedures_for_using_PepQuery_01232018.pdf). Please check the error message as follows.

> Forbidden
You don't have permission to access this resource.

**Comment by wenbostar** [comment]
Please try again.

**Comment by cvn001** [comment]
Thanks. I have got these files.

**Comment by cvn001** [comment]
Sorry. I have one more reguest. As I found there was no other example data and scripts as follows in the version 1.4.1 package. Would you please tell me how to download the version 1.0 package? 
![1581619963876](https://user-images.githubusercontent.com/4339335/74468049-242ab280-4ed5-11ea-8890-6c91e6601562.jpg)

**Comment by wenbostar** [comment]
I would suggest you use the latest version since we did a lot of updates.

**Comment by cvn001** [comment]
Thanks . I will try to use the latest version. But I still wish to get some other examples, such as VCF, BED or GTF format files as well as the genome annotation database. Could you please give me some suggestions?
