### ISSUE TITLE
webserver 2 (Pepquery against CPTAC proteomics data) gives an error

### ISSUE THREAD

**Issue by VladimirRoudko** [bzhanglab/PepQuery#21]
Hello,

I am running web server version of PepQuery using the following input parameters:

MS/MS dataset: Prospective_Colon_VU
Target event: Protein Sequence
Input sequence: ".."
Reference database: "Refseq"
Scoring algorithm: MVH
Perform unrestricted modification filtering: yes.

and I receive an error:

"Error message: simpleWarning in system(javabin, intern = TRUE): running command 'java -Xmx30G -jar tool/proteinID-1.0-SNAPSHOT.jar -cpu 0 -db data/refdb/hg38_RefSeq_20190910_eTrypsin_c1_f6_v117/hg38_RefSeq_20190910.fasta -fixMod 6 -fragmentMethod 1 -itol 0.05 -tol 10 -tolu ppm -varMod 117 -ms s3://pdc-pepquery/cptac_colon_2019_labelfree/ -minScore 12 -maxVar 3 -c 1 -m 1 -i RSNSKKKGRRNRIPAVLRTEGEPLHTPSVGMRETTGLGC -t 1 -prefix Wed_Mar_25_210050_2020_protein -o result/Wed_Mar_25_210050_2020_protein/ -n 1000 -um' had status 1"

Is there anything I should apply to run the request successfully?

Thank you!
Vladimir

**Comment by wenbostar** [comment]
I just submitted a search and it works. Could you please try again?

**Comment by VladimirRoudko** [comment]
Yes, it seems the output depends on the length of the queued protein. Longer protein, more often the web server outputs an error. Otherwise, the search produces the output.  Could the result depend on the  number of threads submitted per job?

**Comment by wenbostar** [comment]
No. I think it might be the reason that sometimes the network is not stable. You can also use the server 1 where you can find all the datasets available in server 2.

**Comment by VladimirRoudko** [comment]
Ok, thanks a lot!
