### ISSUE TITLE
Understanding sample names in Colon Prospective PNNL Proteome dataset

### ISSUE THREAD

**Issue by VladimirRoudko** [bzhanglab/PepQuery#22]
Hi Bo,

Sorry for the question which is an off-topic and directly not related to pepquery. I doing some peptide identifications in colon prospective PNNL dataset and would like to match my PSM to the actual patient ID - in order to correlate proteome to the genomics. I found it's hard to trace down the sample labels in PNNL dataset to the actual patient. For example, my search gave the following output:

SRQMESLGMK | TMT 10-plex of peptide N-term@0[229.1629];TMT 10-plex of K@10[229.1629] | 30 | 3 | 1,623.888 | -2.562 | 1,623.884 | 542.303 | 21.706 | 0 | 118 | 1 | 995 | 0.002008 | 1 | 0 | Retained | Yes | 09CPTAC_COprospective_W_PNNL_20170123_B3S1_f08:15737:3

however, "09CPTAC_COprospective_W_PNNL_20170123_B3S1_f08" does not match any patient id in supplemental data for Cell 2019 CPTAC paper or metadata stored on CPTAC server.

Thank you for your help,
  ##Vladimir

**Comment by wenbostar** [comment]
You can find the mapping information in this folder: https://cptc-xfer.uis.georgetown.edu/publicData/Phase_II_Data/S045_Colon_Cancer_Vasaikar2019/CPTAC_COprospective_metadata/.

**Comment by wenbostar** [comment]
Please reopen this issue if you still have any questions.

**Comment by VladimirRoudko** [comment]
Ok, thank you!

**Comment by GuidoLeoni** [comment]
> Hi Bo,
> 
> Sorry for the question which is an off-topic and directly not related to pepquery. I doing some peptide identifications in colon prospective PNNL dataset and would like to match my PSM to the actual patient ID - in order to correlate proteome to the genomics. I found it's hard to trace down the sample labels in PNNL dataset to the actual patient. For example, my search gave the following output:
> 
> SRQMESLGMK | TMT 10-plex of peptide N-term@0[229.1629];TMT 10-plex of K@10[229.1629] | 30 | 3 | 1,623.888 | -2.562 | 1,623.884 | 542.303 | 21.706 | 0 | 118 | 1 | 995 | 0.002008 | 1 | 0 | Retained | Yes | 09CPTAC_COprospective_W_PNNL_20170123_B3S1_f08:15737:3
> 
> however, "09CPTAC_COprospective_W_PNNL_20170123_B3S1_f08" does not match any patient id in supplemental data for Cell 2019 CPTAC paper or metadata stored on CPTAC server.
> 
> Thank you for your help,
> ##Vladimir

Dear Vladimir 
did you managed how to solve this issue ? I'm performing a similar analysis on endometrial CPTAc dataset . By using the mapping info I'm able to identify all the samples in a TMT plex but I'm not able to understand how to associate a peptide to a specific patient
Best regards
Guido
