### ISSUE TITLE
Unspecific cleavage 

### ISSUE THREAD

**Issue by EdenGoldfarb** [bzhanglab/PepQuery#23]
Will you consider to add unspecific digestion for immunopeptidomics identifications?

Many thanks,
Eden.

**Comment by EdenGoldfarb** [comment]
Many thanks for the quick replay.
Not sure what do you mean by peptide 'type'. The peptides I hope to validate were identified using 3 reading-frames customized data base and were predicted to bind the relevant MHC class I molecule   (length ~ 8-12). The format is Raw (convertible) and the machine is Q- Exactive-Plus. Data was acquired using a data-dependent “top 10” method, fragmenting the peptides by higher-energy collisional dissociation (HCD).

**Comment by wenbostar** [comment]
Thanks for providing the information. I will send you a tutorial about how to use this function in the next few days.

**Comment by EdenGoldfarb** [comment]
Thanks a lot!

**Comment by wenbostar** [comment]
Hi @EdenGoldfarb, please find the tutorial at http://pepquery.org/document.html#immunopeptidomics. Please let me know if you have any questions.
