### ISSUE TITLE
sample information not shown PepQuery Web version

### ISSUE THREAD

**Issue by gt7901b** [bzhanglab/PepQuery#24]
Hi, Bo:

I tried both TCGA_Breast_cancer_proteome and TCGA_Colon_cancer_proteome. When I selected row in Identification Result, the Sample Information is empty. 

As for TCGA_breast_cancer_proteome,  results in modification column says iTRAQ 4-plex. There seems to be multiple sample names in spectrum title. How will you display sample information? How do I know the query peptide in which sample?

thanks for your time

ww
![2020-05-01_15-04-08pepquery](https://user-images.githubusercontent.com/22965838/80833768-43c0a580-8bbd-11ea-8601-8da04b711ef8.png)

**Comment by wenbostar** [comment]
For **TCGA_Breast_cancer_proteome** dataset, please find sample mapping information in this file: https://cptac-data-portal.georgetown.edu/cptac/documents/CPTAC_TCGA_Breast_Cancer_iTRAQ_Sample_Mapping_r2_S015_S029_Sept2016.xlsx. 

For **TCGA_Colon_cancer_proteome** dataset, please find sample mapping information in this file: https://cptac-data-portal.georgetown.edu/cptac/documents/CPTAC_TCGA_ColorectalCancer_select_clinical_data_r1.xlsx.

The spectrum column in the table contains the sample raw file information.

**Comment by gt7901b** [comment]
Got it. thanks, Bo!
