### ISSUE TITLE
unexpected behavior

### ISSUE THREAD

**Issue by Seb-Leb** [bzhanglab/PepQuery#25]
I am using PepQuery to validate novel peptides and I came across the following unexpected behavior:

My reference db contains the following two sequences:

> >sp|P50395|GDIB_HUMAN Rab GDP dissociation inhibitor beta OS=Homo sapiens OX=9606 GN=GDI2 PE=1 SV=2
> ...TY_MLNKPIEEIIVQNGK_V...

and

> >sp|P06748|NPM_HUMAN Nucleophosmin OS=Homo sapiens OX=9606 GN=NPM1 PE=1 SV=2
> ...FK_VDNDENEHQLSLR_TVS...

and my query file contains the following peptides:
MLNKPIEEIIVQDGK
VDNDEDEHQLSLR

I run the PepQuery search using the following command:
```
java -jar pepquery-1.4.1/pepquery-1.4.1.jar \
-itol 0.05 -hc TRUE -um -cpu 4 -pep search_files/q10767_search.txt \
-db swissprot_UP000005640.fasta -ms spectra/q10767.mgf -o pepq_test/
```
As expected, PSMs with VDNDEDEHQLSLR are not confident because it is one deamidation away from a peptide in the above NPM1 reference and thus receives an equal score.

However, for MLNKPIEEIIVQDGK , we get a confident association to a spectrum even though it is a peptide one deamidation away from a GDI2 peptide as shown above. We expected the same output as with NPM1 and can seem to find an explanation. Could it be because our peptide contains a miss-cleavage? Is there some other explanation?
Thank you!

**Comment by wenbostar** [comment]
Could you send me the files in the output folder?

**Comment by Seb-Leb** [comment]
I'm sorry this was my mistake!
