### ISSUE TITLE
precision on PTM nomenclature

### ISSUE THREAD

**Issue by Seb-Leb** [bzhanglab/PepQuery#26]
I am using the unrestricted modifications feature of pepquery and I would like to filter out some of the modifications based on their unimod classification. I am using the unimod xml to find the modification's specificity and classification but I am not sure what field to use to associate them with the pepquery output. I am mostly interested in the classes "post transnational modification" and "artifact", do you know how I can identify these in the pepquery output?

Thank you

**Comment by wenbostar** [comment]
I will look into this and get back to you soon.

**Comment by wenbostar** [comment]
I just uploaded a new version ([v1.5.0](http://pepquery.org/download.html)) which can generate a modification file (Unimod.tsv) in the output folder that contains detailed modification information including class information you need. Please let me know if it works for your purpose.

**Comment by Seb-Leb** [comment]
that's great thank you!, I will let you know how it goes
