### ISSUE TITLE
Signal-to-Noise-ratio, multiple raw data search

### ISSUE THREAD

**Issue by PTK-kiel** [bzhanglab/PepQuery#27]
Hi developers of PepQuery, 

thank you for this very nice tool. We tried it and with the help of the good instruction it works very nice! I have two question:

1) about the Signal-to-Noise-ratio: Is there any cut-off value (e.g. 0.1 % intensity of the base peak) for the search with PepQuery? Is it possible to manipulate this? The same question is for your visualisation tool PDV: Is there a possibility to manipulate the intensity threshold when a peak is annotated?

2) about the search with multiple raw data files: Because mgf-files are simple text files, is it possible to connect the different mgf-files manually and search against this combined file? Or is there anything why this is not a good idea? Unfortunately, the "msdatasets.json"-file in the documentation is not invocable. 

Thank you very much in advance for your answer! 

Best regards,

**Comment by wenbostar** [comment]
> 1. about the Signal-to-Noise-ratio: Is there any cut-off value (e.g. 0.1 % intensity of the base peak) for the search with PepQuery? Is it possible to manipulate this? The same question is for your visualisation tool PDV: Is there a possibility to manipulate the intensity threshold when a peak is annotated?

For PSM rescoring, in default the cutoff is 5%. If there is no specific reason, I don't recommend to change this. For PDV, we do have an option to change the intensity threshold for peak annotation as shown below. 

![image](https://user-images.githubusercontent.com/5302110/82846461-8fa9f600-9eae-11ea-9388-9b0fef251dbf.png)
![image](https://user-images.githubusercontent.com/5302110/82846495-b0724b80-9eae-11ea-9a66-13c8e7768104.png)

> 2. about the search with multiple raw data files: Because mgf-files are simple text files, is it possible to connect the different mgf-files manually and search against this combined file? Or is there anything why this is not a good idea? Unfortunately, the "msdatasets.json"-file in the documentation is not invocable.

You can directly combine multiple MGF files into one MGF file if they can be searched using the same parameter setting. The output psm_rank.txt file contains spectrum title information for each matched spectrum. Based on the spectrum title information, you will know which raw files the spectra are from. "msdatasets.json" is for multiple datasets with different parameter settings.

**Comment by PTK-kiel** [comment]
Thanks for your helpful answer! The cut-off seems to us very high, because we usually use a a cut-off of 1 % or even 0.1 % of the base peak intensity for our orbitrap data for traditional database searches. Is there therefore a possibility to reduce this cut-off value?

**Comment by wenbostar** [comment]
Different search engines with different scoring algorithms usually use different spectrum preprocessing settings. We have tested the cutoff on orbitrap data and it works good to us. Decreasing the cutoff has the risk to increase false positive hits. What search engine do you use for database search?

**Comment by PTK-kiel** [comment]
We normally use SequestHT for database search.

**Comment by wenbostar** [comment]
The algorithm XCorr used in SequestHT is very different from what we use in PepQuery. A low intensity cutoff like 1% or 0.1% for that may be ok.
