### ISSUE TITLE
index protein database with no cut

### ISSUE THREAD

**Issue by ATPs** [bzhanglab/PepQuery#29]
no enzyme means cutting everywhere. Is there a No cut option? like the -pep?

**Comment by wenbostar** [comment]
What is the purpose of indexing a protein database with no cut (each protein is taken as a "peptide")?

**Comment by wenbostar** [comment]
Please reopen this issue if you still have questions about it.

**Comment by ATPs** [comment]
I only want to test some known peptides (the total size is not small). With no-cut, it is possible to check any possible peptides that I am interested in. Some peptides cannot be generated with normal enzymes.

**Comment by wenbostar** [comment]
Yes. You just need to put these peptides into a file in which one peptide is in one line. Then give the file to "-pep".

Bo

**Comment by ATPs** [comment]
Thank you a lot! I will try it. Best wishes!

**Comment by ATPs** [comment]
For comet, http://comet-ms.sourceforge.net/ there is a function to index the database. My understanding is to build the database head with all possible modifications and different peptides. The benefit is cost of cpu-hours can be reduced greatly. I think my question is, is it possible to have similar function? In my experience, the CPU-hours with a built database (a big database) in comet can be more than 90% saving than using a protein / peptide file directly.

So my question is about speed.... How to make it faster as I need to test a lot of files...

Thanks.

**Comment by wenbostar** [comment]
You could use the indexing function described at http://pepquery.org/document.html#index. This will significantly increase the search speed. Feel free to let me know if you get any questions when you use this function.

**Comment by ATPs** [comment]
> You could use the indexing function described at http://pepquery.org/document.html#index. This will significantly increase the search speed. Feel free to let me know if you get any questions when you use this function.

Yes. Is it possible to index with a pep file only? My case is petty special. There is no protein file but only the peptide file.

**Comment by wenbostar** [comment]
It may be more efficient to have a Zoom meeting to discuss this case if you want.

**Comment by wenbostar** [comment]
The issue was solved through a call.
