### ISSUE TITLE
Broken links on the download page

### ISSUE THREAD

**Issue by umutcakir** [bzhanglab/PepQuery#30]
Hello, 
I want to search on multiple MS/MS datasets, but json file for parameter -c of search_multiple_datasets.py (http://pepquery.org/data/msdatasets.json) is not available now . Besides, example file under multiple datasets (http://pepquery.org/data/msdatasets.tar.gz) is also not available.  I get following error message for them: "You don't have permission to access this resource." 
Is there any alternative link for these files. Can you help me?

**Comment by wenbostar** [comment]
The links should work now. Please try again.
