### ISSUE TITLE
Constructing standalone database for CCLE_proteome_MSV000085836

### ISSUE THREAD

**Issue by andreabc** [bzhanglab/PepQuery#31]
Hello,

To create the ms database for the CCLE_proteome_MSV000085836 data did you use the commands as described in the instructions page:
`msconvert --filter "peakPicking true 1-2" --mgf *.raw`

then `java -cp pepquery-1.4.jar main.java.index.BuildMSlibrary` 

or were there additional steps or arguments?

Thank you,
Andrea

**Comment by wenbostar** [comment]
Hi Andrea,

I used the MSConvertGUI to convert raw data to mgf for the CCLE proteomics data as shown below:

![image](https://user-images.githubusercontent.com/5302110/106924070-54fe8b80-66d4-11eb-9d11-abda5ef0970e.png)

After I got mgf files for all the raw files from CCLE, I ran the following command line to build MS/MS spectra index:

```sh
java -cp pepquery.jar main.java.index.BuildMSlibrary -c 10 -i ccle/mgf/ -o CCLE_proteome_MSV000085836_Index
```
Please use the latest version of PepQuery for this: Version 1.6.0 http://pepquery.org/download.html. 

After the indexing is done, you could use the index by giving "CCLE_proteome_MSV000085836_Index" to the option "-ms" as shown below:

```sh
java -jar pepquery.jar -ms CCLE_proteome_MSV000085836_Index ...
```

Please feel free to let me know if you have any further questions.

Bo

**Comment by andreabc** [comment]
This is perfect, thank you!

**Comment by sophiachen1** [comment]
Hello @wenbostar, I am trying to build index from raw files. Are the parameters you showed to convert and index the same across all datasets in pepquery2 database? Are there any specific parameters I need to tailor according to different datasets? Thank you!
