### ISSUE TITLE
Adding ADP-ribo PTM

### ISSUE THREAD

**Issue by jfcalcul** [bzhanglab/PepQuery#32]
Is it possible to add another PTM which is not in the current list of 159 PTM ?
I would need the unimod 213: ADP Ribose addition
C(15)H(21)N(5)O(13)P(2)
mass: 541.06110901175
site: S
That PTM is mostly found on Serine, but can also be found on other amino acid (PMID : 30157440)
Thanks

**Comment by wenbostar** [comment]
It's possible. I will try to support this modification soon.

**Comment by wenbostar** [comment]
This modification is upported in the latest version.
