### ISSUE TITLE
Additional labeling based quantification (TMT)

### ISSUE THREAD

**Issue by andreabc** [bzhanglab/PepQuery#33]
Hi Bo,

I was wondering if there is a way to include TMT reporter tags (e.g. 126, 127n, ... 130c, 131) in addition to the "TMT 10-plex of peptide N-term"? I have run some analysis on the CCLE proteome dataset but can only narrow down the peptide to a particular 10-plex experiment, not the specific cell line/sample.

(Apologies if this is off topic, this field is new to me)

Thank you,
Andrea

**Comment by wenbostar** [comment]
Hi Andrea,

"TMT 10-plex of peptide N-term" is the modification added to a peptide. All the reporter tags share the same mass before they are fragmented in MS/MS. So you will not see any difference in peptide level (peptide mass or m/z) for the same peptide with different tags (MS1 spectra). 

Bo

**Comment by andreabc** [comment]
Okay, that makes sense. So to clarify, further identification of which peptide comes from which sample in the 10plex isn’t possible with pepquery but with separate analysis? If so, do you have any recommendations? Thank you!

**Comment by wenbostar** [comment]
If you're only interested in the novel peptides identified through PepQuery, you could find sample information by using the sample mapping information in this table [Supplemental Table SI, column "Protein 10-Plex ID" and "Protein TMT Label"](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7339254/bin/NIHMS1569324-supplement-TS1.xlsx) and the spectrum title ("spectrum" column) which contains the raw MS/MS file information.

**Comment by wenbostar** [comment]
It's filename:index. The index is the index (1-based) of spectra in MGF format file (converted from raw MS/MS file).

**Comment by apataskar** [comment]
Hi,

This is exact information I need but I am struggling to find the spectrum ID, but instead of CCLE, I am looking for a match in iTRAQ labels for CPTAC TCGA BC data https://proteomic.datacommons.cancer.gov/pdc/study/PDC000111.

How can I find matching spectrum in this? Any help would be really appreaciated. 

Thank you very much in advance.
