### ISSUE TITLE
label quantification (TCGA BC)

### ISSUE THREAD

**Issue by apataskar** [bzhanglab/PepQuery#34]
Hi,

I have a similar question as Andrea- ie, to find the sample information based on iTRAQ labelling in TCGA BC dataset (instead of Andrea's CCLE analysis);

https://proteomic.datacommons.cancer.gov/pdc/study/PDC000111

The novel peptides that I find with PEPQUERY, I wish to map back to sample. I see it is possible using spectrum ID- but struggling to find spectrum information.

Sorry for being naive- I am very new to this field.

How can I find matching spectrum in this? Any help would be really appreciated.

Thank you very much in advance.

Abhijeet Pataskar

**Comment by wenbostar** [comment]
Hi Abhijeet,

Below is an example to show you how to find sample information for TCGA BC dataset:

For this peptide "SYELPDGQVITIGNEQFR", we could get a match as shown below:
![image](https://user-images.githubusercontent.com/5302110/125865654-5bc3b877-687c-4c56-a17d-06281d11f889.png)


From the dataset link showing in the dataset table at http://pepquery2.pepquery.org/:
![image](https://user-images.githubusercontent.com/5302110/125865222-4fe63fe3-fbe2-4c9d-93f2-750a9f5c9b41.png)

You could find a sample mapping table like below:

![image](https://user-images.githubusercontent.com/5302110/125865823-2ea64d92-ddaf-48a7-9d52-fb8b49a1edd7.png)

Download the Excel file and open it:
![image](https://user-images.githubusercontent.com/5302110/125865444-9569b521-1ac8-42ef-9e49-6e039d132d1f.png)

Then based on the information from the spectrum ID: **TCGA_C8-A12P_BH-A0C1_A2-A0EY_117C_W_BI_20130622_H-PM**_f08:31425:2, you can find which iTRAQ experiment (also the sample IDs in the iTRAQ experiment:  column 114-Biospecimen,115-Biospecimen,116-Biospecimen) this spectrum comes from:

![image](https://user-images.githubusercontent.com/5302110/125866080-17e43efe-4cd7-4bd9-93c9-c6b77ccd56df.png)

Please let me know if this works for you.

Bo

**Comment by apataskar** [comment]
Hi Bo,

Thanks for the quick reply. Very helpful- but,

Thanks, I understand how to get iTRAQ experiment ID for a given peptide. However, how can we map to individual samples, is something I still don’t get?
How do we know if a peptide comes from 114, 115 or 116 bio specimen?

Thanks again !
Abhi


Sent from my iPhone

On 16 Jul 2021, at 00:36, Bo ***@***.***> wrote:

﻿

Hi Abhijeet,

Below is an example to show you how to find sample information for TCGA BC dataset:

For this peptide "SYELPDGQVITIGNEQFR", we could get a match as shown below:
[image]<https://user-images.githubusercontent.com/5302110/125865654-5bc3b877-687c-4c56-a17d-06281d11f889.png>

From the dataset link showing in the dataset table at http://pepquery2.pepquery.org/:
[image]<https://user-images.githubusercontent.com/5302110/125865222-4fe63fe3-fbe2-4c9d-93f2-750a9f5c9b41.png>

You could find a sample mapping table like below:

[image]<https://user-images.githubusercontent.com/5302110/125865823-2ea64d92-ddaf-48a7-9d52-fb8b49a1edd7.png>

Download the Excel file and open it:
[image]<https://user-images.githubusercontent.com/5302110/125865444-9569b521-1ac8-42ef-9e49-6e039d132d1f.png>

Then based on the information from the spectrum ID: TCGA_C8-A12P_BH-A0C1_A2-A0EY_117C_W_BI_20130622_H-PM_f08:31425:2, you can find which iTRAQ experiment (also the sample IDs in the iTRAQ experiment: column 114-Biospecimen,115-Biospecimen,116-Biospecimen) this spectrum comes from:

[image]<https://user-images.githubusercontent.com/5302110/125866080-17e43efe-4cd7-4bd9-93c9-c6b77ccd56df.png>

Please let me know if this works for you.

Bo

**Comment by apataskar** [comment]
In short, in your example, SYELPDGQVITIGNEQFR,

Which iTRAQ bioscpecimen (114,115,116) does it come from ?

**Comment by wenbostar** [comment]
Based on the reporter ion intensity distribution, it looks like this peptide comes from "116 bio specimen" in which the reporter ion intensity is much higher than others.

![image](https://user-images.githubusercontent.com/5302110/125967762-d0b51f28-7d73-4e00-88b5-e2e0b87cf38f.png)

![image](https://user-images.githubusercontent.com/5302110/125967864-43971c87-02ff-40ad-8fc0-319b86944566.png)

**Comment by apataskar** [comment]
Oh I see! Thanks a lot! It means, basically the solution is to map the spectrum title to the 116, 117,118 reporter ion intensities of that particular scan? Am I interpreting it correct?

**Comment by wenbostar** [comment]
Yes. But you could also look for evidence in corresponding genomics or RNA-Seq data from TCGA.

**Comment by apataskar** [comment]
Thanks again! Really amazing 👍
