### ISSUE TITLE
Error when running Pepquery in immunopeptidomics mode

### ISSUE THREAD

**Issue by Zack-Ely** [bzhanglab/PepQuery#35]
Hi,

I have custom MGF files from an immunopeptidomics experiement and a set of predicted neopeptides. I have tried running Pepquery to analyze these data with the following command (as an example):

java -jar /net/pepquery-1.6.2.jar -o /net/pep_output -varMod 75,117 -e 0 -tol 20 -tolu ppm -itol 0.05 -prefix pep_true -ms /net/combined.mgf -pep EEISNLKAAF -db /net/TEST_REF.fasta -n 1000 -m 1 -maxLength 11 -minLength 8 -um -hc FALSE

This command does not return most of the expected outputs (e.g., psm_rank.txt). I have run the command with some 'positive control' self peptides that were detected via Mascot, etc by some colleagues, but even these fail to produce any PSMs (including after removing these peptides from the reference fasta file). This suggests to me that the issue has to do with my parameters or perhaps input preparation. Do you have any suggestions? Is Open-pFind a prerequisite to running Pepquery on immunopeptidomics data? (I use a Mac)

All outputs of this command look something like this:

#############################################
PepQuery parameter:
Fixed modification: 6 = Carbamidomethylation of C
Variable modification: 75,117 = Acetylation of protein N-term,Oxidation of M
Max allowed variable modification: 3
Add AA substitution: false
Enzyme: 0
Max Missed cleavages: 100
Precursor mass tolerance: 20.0
Precursor ion mass tolerance unit: ppm
Fragment ion mass tolerance: 0.05
Fragment ion mass tolerance unit: Da
Scoring algorithm: 1 = Hyperscore
Min score: 5.0
Min peaks: 10
Min peptide length: 8
Max peptide length: 11
Min peptide mass: 500.0
Max peptide mass: 10000.0
Random peptide number: 1000
CPU: 32
#############################################
Input peptide sequences:1
Don't find indexed database:/net/TEST_REF.fasta.sqldb
Use database:/net/TEST_REF.fasta
Load db file: /net/TEST_REF.fasta
Start indexing fasta file

Indexing took 0.822619151 seconds and consumes 31.37724 MB
2021-07-20 21:54:27 [ INFO] Valid target peptides: 1
2021-07-20 21:54:27 [ INFO] Generate peptide objects ...
CPU: 1
Exception in thread "pool-1-thread-1" 2021-07-20 21:54:27 [ INFO] Generate peptide objects done.
java.lang.NullPointerException
	at com.compomics.util.experiment.identification.utils.ModificationUtils.getPossibleModificationSites(ModificationUtils.java:197)
	at main.java.pg.PeptideInput.calcPeptideIsoforms(PeptideInput.java:135)
Build target peptide index done.	at main.java.pg.CreatePeptideInputWorker.run(CreatePeptideInputWorker.java:29)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Finished:10000
Finished:20000
Finished:30000
Finished:40000
Matched spectra: 0
Matched PSMs: 0
Finished:10000
Finished:20000
Finished:30000
Finished:40000
Saved spectra: 0
Get matched spectra done!
2021-07-20 21:55:05 [ INFO] Time elapsed: 0.65 min
Don't find indexed database:/net/TEST_REF.fasta.sqldb
Use database:/net/TEST_REF.fasta
Use enzyme:NoEnzyme
Use enzyme:NoEnzyme
Enzyme: NoEnzyme, maxMissedCleavages: 100
Exception in thread "main" java.lang.NullPointerException
	at com.compomics.util.experiment.identification.utils.ModificationUtils.getPossibleModificationSites(ModificationUtils.java:197)
	at main.java.pg.PeptideInput.calcPeptideIsoforms(PeptideInput.java:135)
	at main.java.pg.DatabaseInput.readDB(DatabaseInput.java:383)
	at main.java.pg.PeptideSearchMT.main(PeptideSearchMT.java:542)

**Comment by wenbostar** [comment]
The output message from PepQuery indicates there is no matched spectrum for the input peptide. What is the parameter you used for the Mascot search?

> Is Open-pFind a prerequisite to running Pepquery on immunopeptidomics data? (I use a Mac)

Using Open-pFind (open search mode) matched peptides for each spectrum as candidates in competitive filtering can significantly improve the speed. If there is no Open-pFind, PepQuery will use its default matching process. This may work in some cases when you have big memory. But I haven't done many testings on this.

How many peptides do you need to do the validation using PepQuery?

**Comment by wenbostar** [comment]
If needed, I'm happy to do Open-pFind search for you.

**Comment by Zack-Ely** [comment]
Hi, 

Thanks so much for the prompt response! I will eventually scan thousands of peptides with Pepquery for this sample. I didn’t do the Mascot search myself, but I will ask my collaborator for the parameters used. He identified >2K peptides that mapped to the reference proteome, however, none of these that I’ve tested generate even a PSM via pepquery, so I think the issue is more likely due to input file preparation (I am new to this).

Do you think the “Exception in thread "main" java.lang.NullPointerException” might explain something? I’ve seen this note output in all of my attempts thus far. 

On a related note, I started by converting and concatenating 2 mzML files to MGF using msconvert in our cluster:

/net/proteowizard/msconvert *mzML --filter "peakPicking true 1-2" --mgf

And got the following warnings:

Warning: vendor peakPicking was requested, but is unavailable as it depends on Windows DLLs.  Using ProteoWizard centroiding algorithm instead.
High-quality peak-picking can be enabled using the cwt flag.
writing output file: ./tk210526_951_ZE_DDAincl2.mgf

Does this help identify the issue? Again I don’t have Windows, so I’m attempting to use the linux installation of ProteoWizard. If you think this issue may be due to the input file preparation, I’d be grateful for any help in resolving it. Happy to communicate directly to facilitate if helpful.

Thanks again!

**Comment by wenbostar** [comment]
> Thanks so much for the prompt response! I will eventually scan thousands of peptides with Pepquery for this sample. I didn’t do the Mascot search myself, but I will ask my collaborator for the parameters used. He identified >2K peptides that mapped to the reference proteome, however, none of these that I’ve tested generate even a PSM via pepquery, so I think the issue is more likely due to input file preparation (I am new to this).

PepQuery is developed to validate novel peptides which are not present in reference proteins. Your input peptides are all novel peptides?

**Comment by wenbostar** [comment]
> /net/proteowizard/msconvert *mzML --filter "peakPicking true 1-2" --mgf

This looks good to me.

**Comment by Zack-Ely** [comment]
Yes, all of the peptides I'm interested in are novel peptides. But as a test to see if I'm doing this properly, I am testing pepquery with a few reference peptides derived from the normal proteome that my colleague identified via Mascot (I excluded these from the reference fasta file in my tests). Do you think the 2 warnings from pepquery ("java.lang.NullPointerException...") and msconvert ("vendor peakPicking was requested, but is unavailable as it depends on Windows DLLs") indicate that the input files may not have been converted properly?

**Comment by wenbostar** [comment]
The output message from PepQuery indicates there is no matched spectrum found from the input mgf. It would be a parameter issue or the peptide doesn't exist in this specific mgf. The peptide you tested is identified from this mgf file: tk210526_951_ZE_DDAincl2.mgf?

>  msconvert ("vendor peakPicking was requested, but is unavailable as it depends on Windows DLLs") indicate that the input files may not have been converted properly?

I saw this before. I don't think there is a problem with the converted mgf.

**Comment by Zack-Ely** [comment]
The peptides I tested were identified from a raw file which was converted to mzML and then to MGF. I will experiment with some parameter changes to see if that helps resolve the issue. I'll mention the solution once I've finished testing over the weekend and then close the issue. Thanks!

**Comment by wenbostar** [comment]
I can help do a test if you could share the raw data and some example peptides with me.
