### ISSUE TITLE
analysis of CPTAC PNNL files

### ISSUE THREAD

**Issue by GuidoLeoni** [bzhanglab/PepQuery#36]
Dear Team  I would reanalyze CPTAC data (endometrial PNNL files ) for some peptides of my interest. I'm new to proteomic analysis :-). 
I downloaded 16 PNNL from the cptac site. Each PNNL is the combination of 10 TMT plexes with different samples from different patients pulled together. I'm able to analyze the raw files (after converting them in mgf with msconvert) and for each file i extract a list of significant peptides in the pool but I would like to know also the  intensity levels of the peptides from each different sample.  Therefore I suppose that I should associate to the found peptides, the  “TMT reporter ion” intensity from the different TMT channels, e.g., 127C, 128N, 
Is there a way to achieve this goal with pepquery?

Here it is my code 
java -Xmx10G -jar /databis/pepquery-1.6.2/pepquery-1.6.2.jar -o ‘‘pep’’ -fixMod 6,62,108 -varMod 117 -tol 10 -tolu  ppm -um -itol 0.05 -prefix ‘‘pep’’ -t 1 -ms 01CPTAC_UCEC_W_PNNL_20170922_B1S1_f01.mgf -i "extended10FSP.fa" -db "/data/PIPELINE/GENOMES/hg38/TRANSLATECDS2.0/sequence.fasta" -n 1000 -m 1 -maxLength 50 -minLength 5 -um -hc FALSE -cpu 10

**Comment by wenbostar** [comment]
Could you look at this issue #34 ?

**Comment by GuidoLeoni** [comment]
Thank you
I'm sorry for the basic question but:
I read the issue #34
Where i can find the reporter ion intensity info?

**Comment by wenbostar** [comment]
If you use the standalone version, you can find the reporter intensity in the mgf file from the output folder of PepQuery.
