### ISSUE TITLE
Indexing and modification

### ISSUE THREAD

**Issue by XiaofengxBjmu** [bzhanglab/PepQuery#37]
Dear：
I was recently using pep to process cptac data, but the following error was reported

> 2021-11-04 15:14:32 [ INFO] Generate peptide objects ...
> 2021-11-04 15:14:32 [ INFO] Generate peptide objects done.
> Exception in thread "main" org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: msmsdb)
>         at org.sqlite.core.DB.newSQLException(DB.java:909)
>         at org.sqlite.core.DB.newSQLException(DB.java:921)
>         at org.sqlite.core.DB.throwex(DB.java:886)
>         at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
>         at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
>         at org.sqlite.core.DB.prepare(DB.java:227)
>         at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:41)
>         at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
>         at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
>         at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:48)
>         at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:263)
>         at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:235)
>         at main.java.pg.SpectraInput.readMSMSdb2(SpectraInput.java:319)
>         at main.java.pg.PeptideSearchMT.main(PeptideSearchMT.java:451)

my command is:

> java -cp pepquery-1.6.2.jar main.java.index.BuildMSlibrary -c 12 -i TCGA-2014/ -o test_all
> 
> java -Xmx24G -jar pepquery-1.6.2.jar -o out2 -fixMod 6 -varMod 117 -tol 20 -tolu ppm -um -itol 0.5 -prefix pepout -ms test_all -pep input.fa -n 1000 -db uniprot.fa -maxLength 50 -minLength 5 -maxVar 5 -um -cpu 12 -indexType 1

How can I resolve the error？ Looking forward to the reply

**Comment by wenbostar** [comment]
It looks like the folder **test_all** doesn't exist in the working folder when ran:
```sh
java -Xmx24G -jar pepquery-1.6.2.jar -o out2 -fixMod 6 -varMod 117 -tol 20 -tolu ppm -um -itol 0.5 -prefix pepout -ms test_all -pep input.fa -n 1000 -db uniprot.fa -maxLength 50 -minLength 5 -maxVar 5 -um -cpu 12 -indexType 1
```
Could you double check if test_all is there?

**Comment by XiaofengxBjmu** [comment]
I have other question. How can I resolve the error？ Looking forward to the reply

> Indexing took 0.899028825 seconds and consumes 82.195392 MB
> Ignore peptide (reason: exist in reference database): IEEEWKTKEMLILTRMAEDVKR
> Ignore peptide (reason: exist in reference database): LAGNAVYTKPSFTQEHKAAVSVLKPFSKGTPSTSSPAKALPQVRDR
> Ignore peptide (reason: exist in reference database): LKQLSNGTLKNDNGGTCQSPALPALVRPPAPPLQPSLDIKPFLPFPIDTAAAVNLFPNFNAMDPIQKAVINHTFGVPLPHRR
> Ignore peptide (reason: exist in reference database): MRNIMYFGGTCQSPALPALVRPPAPPLQPSLDIKPFLPFPIDTAAAVNLFPNFNAMDPIQKAVINHTFGVPLPHRR
> Ignore peptide (reason: exist in reference database): SFKNNLVDIIQQNKERWKELAAQEAR
> 2021-11-22 17:14:44 [ INFO] Valid target peptides: 571
> 2021-11-22 17:14:44 [ INFO] Generate peptide objects ...
> CPU: 16
> Exception in thread "pool-1-thread-11" Exception in thread "pool-1-thread-6" Exception in thread "pool-1-thread-3" Exception in thread "pool-1-thread-7" Exception in thread "pool-1-thread-2" Exception in thread "pool-1-thread-12" Exception in thread "pool-1-thread-14" Exception in thread "pool-1-thread-16" java.lang.NullPointerException
> 	at com.compomics.util.experiment.identification.utils.ModificationUtils.getPossibleModificationSites(ModificationUtils.java:197)
> 	at main.java.pg.PeptideInput.calcPeptideIsoforms(PeptideInput.java:135)
> 	at main.java.pg.CreatePeptideInputWorker.run(CreatePeptideInputWorker.java:29)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Exception in thread "pool-1-thread-20" java.lang.NullPointerException
> 	at com.compomics.util.experiment.identification.utils.ModificationUtils.getPossibleModificationSites(ModificationUtils.java:197)
> 	at main.java.pg.PeptideInput.calcPeptideIsoforms(PeptideInput.java:135)
> 	at main.java.pg.CreatePeptideInputWorker.run(CreatePeptideInputWorker.java:29)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by XiaofengxBjmu** [comment]
my mod_para is

-fixMod 6,62,108 -varMod 75,114,117,118,128

**Comment by XiaofengxBjmu** [comment]
Dear:
This is printed when the program runs successfully, and there are a lot of them. I don't know the reason. Thanks

> File doesn't exist:05_gbm_out/178058.mgf
> File doesn't exist:05_gbm_out/178060.mgf
> File doesn't exist:05_gbm_out/178064.mgf
> ...

**Comment by wenbostar** [comment]
> Dear:
This is printed when the program runs successfully, and there are a lot of them. I don't know the reason. Thanks
File doesn't exist:05_gbm_out/178058.mgf
File doesn't exist:05_gbm_out/178060.mgf
File doesn't exist:05_gbm_out/178064.mgf

This is not an error message. It means for some peptideforms, PepQuery didn't find matched MS/MS spectra based on the mass values of peptideforms in the indexed MS/MS library. This is normal. This message is for debugging purpose. In your case, you could ignore this.

**Comment by wenbostar** [comment]
> my mod_para is
-fixMod 6,62,108 -varMod 75,114,117,118,128

Could you change 75 to 21?
21 Acetylation of peptide N-term 42.0105646837 modn_peptide

Since the purpose is to validate specified peptides and inputs are peptide sequences, PepQuery doesn't know if an input peptide is from a protein N-terminal or not. Therefore, if you want to consider acetylation of protein N-term, use "Acetylation of peptide N-term" instead. This will solve this problem.

**Comment by XiaofengxBjmu** [comment]
Thanks a lot!
