### ISSUE TITLE
Searching large datasets

### ISSUE THREAD

**Issue by XiaofengxBjmu** [bzhanglab/PepQuery#38]
Hi,
I have some questions about pepquery. I'm using pepquery find some peptides, which were searched using comet against Uniprot db. MS raw data set were downloaded from PRIDE. Only three data sets had results, and all the others had bugs. My parameter are:

> Fixed modification: 6 = Carbamidomethylation of C
> Variable modification: 21,114,117,118,128 = Acetylation of peptide N-term,Phosphorylation of Y,Oxidation of M,Phosphorylation of T,Phosphorylation of S
> Max allowed variable modification: 5
> Add AA substitution: false
> Enzyme: 1
> Max Missed cleavages: 2
> Precursor mass tolerance: 20.0
> Precursor ion mass tolerance unit: ppm
> Fragment ion mass tolerance: 0.5
> Fragment ion mass tolerance unit: Da
> Scoring algorithm: 1 = Hyperscore
> Min score: 12.0
> Min peaks: 10
> Min peptide length: 5
> Max peptide length: 50
> Min peptide mass: 500.0
> Max peptide mass: 10000.0
> Random peptide number: 1000
> CPU: 32

First, I search 200 peptide with pepquery in a data set (32 mgf files), I met this:

> pool-3-thread-13 -> Finished 137: LVQDIANNTNEEAGDGTTTATVLAR .
> pool-3-thread-2 -> Finished 99: LVQDVASNTNEEAGDGTTTATVLAR .
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 14
>     at main.java.pg.RankPSM.rankPSMs(RankPSM.java:44)
>     at main.java.pg.PeptideSearchMT.main(PeptideSearchMT.java:682)
> End Bye!

I search only 200 peptide with pepquery in next dataset(9 mgf file), there is a outofmemory bug. I give 110G memory, is that still not enough？

> pool-3-thread-29 -> Finished 102: SAAEMYGSVTKHPSPSPLLSSSFDLDYDFQR .
> pool-3-thread-7 -> Finished 33: KEEVEEDNEVSSGLKQNYDEMSPAGQISK .
> pool-3-thread-22 -> Finished 152: PASLYQSSIDRSLERPMSSASMPSDFRK .
> Exception in thread "main" java.lang.OutOfMemoryError
>     at java.lang.AbstractStringBuilder.hugeCapacity(AbstractStringBuilder.java:161)
>     at java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:155)
>     at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
>     at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
>     at java.lang.StringBuilder.append(StringBuilder.java:136)
>     at java.lang.StringBuilder.append(StringBuilder.java:131)
>     at org.apache.commons.lang3.StringUtils.join(StringUtils.java:4132)
>     at org.apache.commons.lang3.StringUtils.join(StringUtils.java:4177)
>     at main.java.pg.PeptideSearchMT.main(PeptideSearchMT.java:643)

I search 200 peptide with pepquery in next dataset(31 mgf file), there is a kill bug. Why is that?

> pool-3-thread-5 -> Finished 75: SIRGSKKPTNDSNPSR .
> pool-3-thread-5 -> Start 79: ESCTEEIVSEAESHVSGISR ...
> /var/spool/slurmd/job10720637/slurm_script: line 25: 25038 Killed                  java -Xmx110G -jar pepquery-1.6.2/pepquery-1.6.2.jar -o pride_out/${outdir} -cpu 32 -fixMod 6 -varMod 21,114,117,118,128 -tol 20 -tolu ppm -um -itol 0.5 -prefix pepqout -ms ${pepin}/${input} -pep ${fasta} -n 1000 -db 2020-11-26-reviewed-contam-UP000005640.fa -maxLength 50 -minLength 5 -maxVar 5 -indexType 1

Thank you very much in advance.

**Comment by XiaofengxBjmu** [comment]
If the data set has 30 mgf files and I want to search for 2000-4000 peptides, how do I allocate computational resources. I give 32CPU and 512GB memory.However, errors often occur and premature termination occurs.

Now I only search for 200 peptides at a time and still get bugs frequently, such as out of memory. Even with 32 cpus, I could probably only complete 10-20 peptides per hour, Is this normal?

Should I reduce to 50 peptides? That means I need 50 groups for one dataset, and I have 40 dataset, Is there a better way？

MS are labelfree and from Q Exactive or LTQ Orbitrap.

**Comment by wenbostar** [comment]
> Hi, I have some questions about pepquery. I'm using pepquery find some peptides, which were searched using comet against Uniprot db. MS raw data set were downloaded from PRIDE. Only three data sets had results, and all the others had bugs. My parameter are:
> 
> > Fixed modification: 6 = Carbamidomethylation of C
> > Variable modification: 21,114,117,118,128 = Acetylation of peptide N-term,Phosphorylation of Y,Oxidation of M,Phosphorylation of T,Phosphorylation of S
> > Max allowed variable modification: 5
> > Add AA substitution: false
> > Enzyme: 1
> > Max Missed cleavages: 2
> > Precursor mass tolerance: 20.0
> > Precursor ion mass tolerance unit: ppm
> > Fragment ion mass tolerance: 0.5
> > Fragment ion mass tolerance unit: Da
> > Scoring algorithm: 1 = Hyperscore
> > Min score: 12.0
> > Min peaks: 10
> > Min peptide length: 5
> > Max peptide length: 50
> > Min peptide mass: 500.0
> > Max peptide mass: 10000.0
> > Random peptide number: 1000
> > CPU: 32
> 
> First, I search 200 peptide with pepquery in a data set (32 mgf files), I met this:
> 
> > pool-3-thread-13 -> Finished 137: LVQDIANNTNEEAGDGTTTATVLAR .
> > pool-3-thread-2 -> Finished 99: LVQDVASNTNEEAGDGTTTATVLAR .
> > Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 14
> > at main.java.pg.RankPSM.rankPSMs(RankPSM.java:44)
> > at main.java.pg.PeptideSearchMT.main(PeptideSearchMT.java:682)
> > End Bye!

Is this dataset from a phosphoproteomics experiment? Could you share all the inputs with me so that I can reproduce this error?

**Comment by XiaofengxBjmu** [comment]
These three bugs are from three phosphoproteomics experiment data set. 

First error from PXD004415. My input file:

KATLQPVLQLK
SMMSPMAECSMMSAYER
KQPPVSPGTVLVGSQK
EDGNEENKENQGDETQGQQPPQR
STGVFQDEELLFSYK
KGEAPETNTDETPKK
GEVMGDNLLLSSVFQFSKK
APMGSGQEAAVPVTWTEIFSGK
QALAWMVSRENSKELPPFR
IFHGSGVGNPFGPR
IHRASDPGFPAEEPKEK
SGPKPFSASKPQTSPSPKR
SLGQNPTEAELPDMINEVDADGNGTIDFPEFLTMMAR
GALEGLPRPPPPVKVVVLRTPAEEDGGGK
SLGQNLTEAELQDMINEVDADGNGTIDFPEFLTMMAR
SLGQNPTEAELQDMISEVDADGNGTIDFPEFLTMMAR
SPGVISSASTALSQDIPEIASEALSR
DQFPEVYVPTVFQNYVADIEVDGK
SLGQNPTEAELQDMVNEVDADGNGTIDFPEFLTMMAR
QAVAISAGQILVAKASSSVSKAVGPK
SSLNEYQPELYQVLDDGK
QLQDLVAMVQDDDAAQGVISASASNLDDFYPAEEDTKENSNNTR
EPVEEATKSPSDVNISAQPALSNFISQLEPEVFNSLVK
SLGQNPTEAELQDMIIEVDADGNGTIDFPEFLTMMAR
AALGLQDSDDEDAAIDIDEQIESMFNSK
NILTDEGEPTDEETTGDISDSMDFVLLNFAEMNK
QQFHSKPVDADSDDDPLEAFMAEVEDQAAR
QQSHSKPVDSDSDDDPLEAFMAEVEDQAAR
IIPTLEEGLQLPSPTASSQLPLESDAVECLNYQHYK
TLPYLVSNVIELQDVDPNDQEEDGANIDLDSQR
AITIAGVPQSVTEYVKQICLVMLETLSQSPQGR
LSSNNALIEFLLEGTPEIR
MDKYADLSDTELTTLLR
ISLATPLQLYKSSNMTQRWQR
MEDSMDMNMSPLRPQNYLFGCELK
MEDSMDMDMTPLRPQNYLFGCELK
QTPVDSPDDSTISESANQVFLGFTYVAPSVLESVK
LGDFGSASIMASANSFVGTPYWMAPEVILAMDEGQYDGK
NVIDEWTEKALQKMELNQLTEEDR
KASGPPVSELITKVVAASK
LGDFGSASIMAPASSFVGTPYWMAPEVILAMDEGQYDGK
NGRMEIIANDQGNR
AHQLVLPPCDIVIKAVADYVR
AIEEDNNFSK
VNVPEESRDGETSPR
EAAAQEAGADTPGKGQPPAPKSPPK
TETEEKNPLPSKETIEQEK
DSRPSQAAGDNQGDEAKEQTFSGGTSQDTR
DFIIQTGNPTGTGR
VTHTETGKVLFGPEAPKASQLGAWLEMNPGYEVAPR
SKSEEAHTEDSVMDHHFR
VEILSNDQGNR
SLGHPEPLSDGRPQGNSR
EVDEQMINVQNK
ELIDASDKEGMSPAKR
KESKEEQTSIDVAGKPNEVTK
EVEDKESEGEEEDEDEDISK
MREIVHIQAGQCSNQIGAK
MREVVHLQAGQCGNQIGAK
MWVTNGGKANWYFLLARSDPDPK
QIPLERIIVETDASYFLPR
SLHIATIEK
HTGPNSPDMANDGFVR
KQEESADAGAPSGK
MSMKEVDEQMINVQNK
TRLSPPRASYDDPYQK
ALSHQKPMVSTQPAPR
MSCFTRPSMSPTPLDR
KLAILPEPR
SKNRNSNVLPYDYNR
AKPAKPQDSVPSPR
EGQENQGLTKDYGNSPLHR
SLENETLNKEENCHSPTSKPPKPDQPLK
NQVEEDAEDSGEADDEEKPEIHKPGQDSFSK
GDFYIIEYAACDATYNEIVTLER
MREIVHIQASQCGNQIGAK
LQQAVMLGALTEVPVPARFLFILLGPKGK
VQAMQISSEKEEDDNEERQDPGDNWEEGGGGGGGMEK
RYSSSISSSPQKDLTQAK
LKEDILENEDEQNSPPRK
VASASAGSCDVPSPFNHRPGSHLDSHQR
ALSHQEPMDSTQPAPR
EHEKEVLQKAIEEDNNFSK
EQYQQQQQWGSRGGFVGR
KLSLDTDAQFGHGSDYSR
NTNNANSCQIIIPQNQVNRK
MREIVHIQAGQCGIQIGAK
KFGVESDQRVTNDISPESSPGVGR
GNNFLYTDGK
STAQQEPDGKPASPTPVIVASHTANKEEK
GGPATPPPKGAPTPPAATPPSLKGGLATPPNK
ELTSICSPIISKPKPK
IKVPEQLKPSVSQPQPANSNNGTSTATSTNNNAK
KADMMESLVLGFDDGK
ELTNTCSPIISKPKPK
RFAFPLSLSQGSSDGVEVR
STSFRQGPKESGLGDGTGPK
TVPKTVDNSVALATGEKGFGYK
VGMVETNSQNRPVDDVK
KGSVVNVNPTDTRPQSDTPEIR
VDFNVPMKNNEITNNQR
KNNRQPYAVSELAGHETSAESWGTGR
TGNSIPHPATGKTVANLLSGKSPR
VDFNVPMKNDQITNNQR
RLDISPSTFRK
TSMSTPHVAEPAENEQDEQDENGAEASADLR
KNVLCGNIPPELFARMTAEEMASDELK
KKEIEELESQAQALSQEGK
CITDTLQELVNQSKAAHQSPSVPK
GKYGTMSEGRSEDNLSATPPALR
KSISPGR
CLGPPSPPAPPR
TPGGPTKPTSSSCMGFEGANK
FSDLSEAANRNNDALR
KNCTYTQVQTHSSDEPMTTFVVCNECGNR
NGNECAYHHPISPCKAFPNCK
AIRLELEGPRGSPNAR
SPSTPKSPGASNFSTLPKISPSSLSNNYNNMNNR
ERSPSPLWGNVVPSPLPTRR
SLQEAQQQLEEVRQNR
YLTEHPDPDNENIVGYNNK
KREENTSNESTDVAK
TSMSTPHVAEPAENEQDEQDENGAEASADLRADAMAK
HIEPELAGRDSPIRAEMPGNIQHYGR
NIAKTESSPSEASQHSMQSPQETTLILPTQQVR
QVDLESDPQNRSPESRPSVVYPSTK
SRSAPPNLWTAQR
SRSAPPNLWASQR
RVNSNGEESPGSSEFFQEAVSHGK
RAPFDLFENKK
TGISDVFAKNNLAVVDVR
GQSTGKGPPQSPVCEGVYNNSR
VNDILIVPYRK
LFRPSSPAPAAPGAR
APTKPPVGPQTSPLKDNPSPEPQLDDIKR
MEMKVWDPDNPLTDRQIDLFLVVAR
SRPFTVAASFKSTSVKSPK
GQSTGKGPPQSPVFEGVYNDSR
TGSETPQAPMSGVGPVSGGPGGFGRGSQGGNFEAPNKR
VNGLDGIAIQQISAGTSHSLAWTALPRDRQVVAWHR
KYEMFSQTLQQSR
TKENDAHLVQVNLNNIK
NLEQILDGGESPKQKGQEIK
EKEQSPTAEEDEDEENDASLANSSTTTLEDKGPGHATFGR
NNQQVPENTEELGQTKPTSNPQVVDEGGAKPELASQATEGSK
NNQQVPENTEELGQTKPMSNPQVVNEGGAKPELASQATEGSK
TLDSDEEWPRPAPPDWSHMR
NKPRSPMVELSKVPLVQR
VDFSVPMKNNQITNNQR
IVGSASPEEEQEKPILDRPTR
NGTTIIQGALTQLIQLYHR
TESSPSEASQHSMQSLQKTTLILPTQQVR
NPDIERPTYTNLNR
NLDVERPTYTNLNR
RLEAAYLDIQR
HFRRDSFDDLGPSLNPVLDYDHGSR
SGLEPTSSPSKGSEPRPLVPPVSGHATIAR
NTNNANSCQIIIPQNQVNR
GMGFTEEEFKR
LLIANTGMDTDKIK
LSSQISAGEEKWNSISPASAGKR
LSSQISAGEEKWNSFSPASAGKR
IHLMAYQLQLQAASNFKSPVK
LHAASYLPAARTGPVAGGLLSPAR
NIAKTEASPSEASQHSMQSPQKTTLILPTQQVR
NLEQILDGGESPKQK
QTDPSTPEQESSKPLGGIQPSSQTIQPK
IIGGDPKGNNFLYTDGK
TKVEATKNETSAPFEERPTPSLNNNCTTSEDSLVLYNR
NNNTDLVILK
APQSIPPSASYPCAAPRPGAPETTALHGGFQR
NCTYTQVQTHSSDEPMTTFVVCNECGNR
VDFNVPMKNNQITDNQR
ENNTITIYSTINHSK
TSKAETPTESVSEPEVATKQELQEEEEETKPPR
AASPPKPLLSNASATPVGR
AKQDFLKTDSDSDLQLYEEQGEGQGDR
RLSTIILHGGGTVCR
GGEQINKIQEDSGCKVQISPDSGGLPER
SNSVEKPMSSILSR
ASPSCSSPTRNSSGVPVSKELLTAGSDGR
ADMLCNSQSNDILQHEGSNCGGTSNKHSLEEDEGSDFITENR
LQAALDDEEAGDRPAMEPGNGSLDLGGDSAGR
CSDVSELSSSPPGPYHQETYVCKPEER
CSDVSELSSSPLGPYHQEPYVCKPEER
TGSETPQAPMSGVGPVSGGPGGFGRGSQGGNFEAPNK
LQQGAGLESPQGQPEPGAASPQRQQDLHLESPQRQTEYSPESPR
QIAESKEDDDVIVNKPHVSDEEEEEPPFYHHPFK
NRTPSDVEELVLDNSR
SVEMHHEALSKALPGDNVGFNVK
QIAQSKEEDDVIVNKPHVSDEEEEEPPFYHHPFK
IISNSSCTTNCLAPLAK
NRNSNVLPYDYNRVPLK
GRMSMKEVDEQMINVQNK
IYHLPDAQSDEDEDFKEQTR
LKCGSGPVHISGQHLVAVEEDAQSEDEEEEDVK
IYQLPDAESDEDEDFKEQTR
ICHLPDAESDEDEDFKEQTR
GAWGNDMNSGLNKSPPLGGAQTISK
DLDIERPTYTNLNR

**Comment by XiaofengxBjmu** [comment]
What is the reason for always running out of memory? I read in the article that only 64GB is used and 799 peptide inputed. My input is 200 peptides and 110GB memory. Is it because I didn't set the parameters right？

**Comment by XiaofengxBjmu** [comment]
Some out of memory have log files. Like this:

> Memory: 4k page, physical 263533436k(12462116k free), swap 0k(0k free)
> 
> vm_info: OpenJDK 64-Bit Server VM (25.102-b14) for linux-amd64 JRE (1.8.0_102-b14), built on Sep 14 2016 12:54:17 by "mockbuild" with gcc 4.8.5 20150623 (Red Hat 4.8.5-11)
> 
> time: Mon Nov 29 15:32:19 2021
> elapsed time: 212843 seconds (2d 11h 7m 23s)

**Comment by wenbostar** [comment]
For the dataset PXD004415, could you try to use the following setting? This dataset was generated using QE, so the error window for MS/MS fragment ion mass values should be set as 0.05 or a similar value. The value of 0.5 you used is too large.

In addition, I also set `-maxVar` as 3 rather than 5 to reduce search space. A peptide with 5 variable modifications is very rare.
```
java -Xmx32G -jar pepquery-1.6.2.jar -o out2 -fixMod 6 -varMod 117,114,118,128,21 -tol 10 -tolu ppm -um -itol 0.05 -prefix pepout -ms test_all -pep pep.tsv -n 1000 -db reference_db.fasta -maxLength 45 -minLength 7 -maxVar 3 -um
```

**Comment by XiaofengxBjmu** [comment]
Thanks! ArrayIndexOutOfBoundsException and 25038 killed is also 0.5Da too large?

**Comment by wenbostar** [comment]
Let me do a test on this dataset. Could you send me your database for "-db"?

**Comment by XiaofengxBjmu** [comment]
[reviewed-contam-UP000005640.fa.zip](https://github.com/bzhanglab/PepQuery/files/7708436/reviewed-contam-UP000005640.fa.zip)

**Comment by wenbostar** [comment]
I downloaded all the raw files from this dataset PXD004415. In total, there are 2409997 MS/MS spectra. Below is the command line I'm using to run PepQuery:

```sh
java -Xmx32G -jar pepquery-1.6.2/pepquery-1.6.2.jar -o out2 -fixMod 6 -varMod 117,114,118,128,21 -tol 10 -tolu ppm -um -itol 0.05 -prefix pepout -ms all.mgf -pep pep.txt -n 1000 -db test/reviewed-contam-UP000005640.fa -maxLength 45 -minLength 7 -maxVar 3 -um
```
It has been running for one hour and I don't see any error so far. The momery usage so far is less than 10G. Will update to you tomorrow once it's finished.

If you're using PepQuery in a cluster, could you tell me how you submit your job and how you request momery and cpu?

**Comment by wenbostar** [comment]
The analysis is finished without any error. It took about 150 min. The max memory looks less than 13G. I used PepQuery v1.6.2.
```
Identified peptides after PTM searching: 91
Identified PSMs after PTM searching: 691
Annotate best PSMs from unrestricted modification searching ...
Generate annotation data for best matches from unrestricted modification searching:1448
2021-12-14 01:19:18 [ INFO] Time elapsed: 153.12 min
2021-12-14 01:19:18 [ INFO] End.
```

**Comment by XiaofengxBjmu** [comment]
Thanks a lot. Let me run it again

**Comment by XiaofengxBjmu** [comment]
Hi, all QE dataset get the result, but LTQ Orbitrap dataset are still too slow, like PXD002022. 
The param is -tol 20 -tolu ppm -itol 0.5, is there anything wrong?
Thank you very much in advance.

My peptide file is attached.

[PXD002022.txt](https://github.com/bzhanglab/PepQuery/files/7729285/PXD002022.txt)

**Comment by wenbostar** [comment]
Could you send me your PepQuery command line for this dataset?

**Comment by XiaofengxBjmu** [comment]
Like this, thanks a lot
> java -Xmx64G -jar pepquery-1.6.2/pepquery-1.6.2.jar -o PXD002022 -cpu 32 -fixMod 6 -varMod 21,114,117,118,128 -tol 20 -tolu ppm -um -itol 0.5 -prefix pepqout -ms PXD002022 -pep PXD002022.txt -n 1000 -db 2020-11-26-reviewed-contam-UP000005640.fa -maxLength 45 -minLength 7 -maxVar 3 -indexType 1

**Comment by XiaofengxBjmu** [comment]
Sorry for other question about scan number. Apologies if this is off topic, this field is new to me

The spectrum_title I get from pepquery is:

> 20111225_EXQ5_KiSh_SA_LabelFree_HeLa_Phospho_Control_rep4_FT1:7834:2

The Spectrum I get from Comet is:

> 20111225_EXQ5_KiSh_SA_LabelFree_HeLa_Phospho_Control_rep4_FT1.10503.10503.2

The ID from MSGF is:

> SpecFile	SpecID	ScanNum
> 20111225_EXQ5_KiSh_SA_LabelFree_HeLa_Phospho_Control_rep4_FT1.mzXML	scan=67845	67845

These are all the same peptides in the same file, but Spectrum Id is different. The Spectrum Id/ScanNum of all results of the three tools don't match. Aren't the ScanNum the same？

Thank you very much in advance.
<img width="1177" alt="截屏2021-12-18 上午1 09 27" src="https://user-images.githubusercontent.com/75332489/146581939-544e273f-ad43-4dd6-a98a-d8abf7a509d9.png">

**Comment by wenbostar** [comment]
It looks like they are from different spectra.

**Comment by XiaofengxBjmu** [comment]
Thanks.
Is there anything wrong for searching PXD002022. It only ran 200 peptides in three days.

**Comment by wenbostar** [comment]
I don't find any obvious problem so far. Maybe you could split your peptide list into multiple files and submit multiple jobs if you use a cluster.

**Comment by XiaofengxBjmu** [comment]
Sorry for another question.
If I want to search CPTAC Phosphoproteome data with **TMT11** and using **Thermo Orbitrap Fusion Lumos**, will the PepQuery command line be right? I tried to run it once but got no results.

java -Xmx64G -jar pepquery-1.6.2/pepquery-1.6.2.jar -o cptac -cpu 32 -fixMod 6,62,108 -varMod 21,114,117,118,128 -tol 20 -tolu ppm -um -itol 0.5 -prefix pepqout -ms cptac -pep cptac.txt -n 1000 -db 2020-11-26-reviewed-contam-UP000005640.fa -maxLength 45 -minLength 7 -maxVar 3 -indexType 1

If TMT6 and Q Exactive, changing command line to -tol 10 -tolu ppm -um -itol 0.05 will be right?

Thank you very much in advance.

**Comment by wenbostar** [comment]
For both TMT11 from CPTAC phospho data and TMT6 generated by QE, the parameter -itol should be set to 0.05 or a similar value.

**Comment by wenbostar** [comment]
Except -itol, I don't find any other obvious problem for your setting.
