### ISSUE TITLE
Get the results different from PepQuery Online

### ISSUE THREAD

**Issue by XiaofengxBjmu** [bzhanglab/PepQuery#39]
Dear Team,
I tried to search for a peptide SRPMTVPSIDDYGR in the CCRCC_Phosphoproteome, but I got different results from pepquery online, and there are many such cases. How did this difference happen and how to improve the true positive rate of the results and get rid of the unreliable results？Thanks a lot.

My result:

> charge                                                            3
> confident                                                       Yes
> exp_mass                                                    1981.82
> modification      TMT 10-plex of peptide N-term@0[229.1629];Phosphorylation of T@5[79.9663];Phosphorylation of S@8[79.9663]
> mz                                                          661.614
> n                                                                 1
> n_db                                                              0
> n_ptm                                                             0
> n_random                                                          1
> pep_mass                                                    1981.86
> peptide                                              SRPMTVPSIDDYGR
> ppm                                                         18.1515
> pvalue                                                     0.001998
> rank                                                              1
> score                                                       12.1771
> spectrum_title        10CPTAC_CCRCC_P_JHU_20180123_LUMOS_f02:8038:3
> total_db                                                          9
> total_random                                                   1000

Pepquery Online:
<img width="480" alt="截屏2022-03-02 上午4 12 29" src="https://user-images.githubusercontent.com/75332489/156241642-2932d3eb-aaac-4b86-a3ce-002411796131.png">

My param:

> java -Xmx64G -jar pepquery-1.6.2/pepquery-1.6.2.jar -o cptac_out/${input}/${search} -cpu 16 -fixMod 6,62,108 -varMod 21,114,117,118,128 -tol 20 -tolu ppm -um -itol 0.05 -prefix pepqout -ms ${pepin} -pep ${fasta} -n 1000 -db 2020-11-26-reviewed-contam-UP000005640.fa -maxLength 45 -minLength 7 -maxVar 4 -indexType 1

**Comment by wenbostar** [comment]
Could you send me the psm_rank.txt file generated by the command line version?

**Comment by XiaofengxBjmu** [comment]
Thanks. This is the psm_rank.txt
[psm_rank.txt](https://github.com/bzhanglab/PepQuery/files/8164539/psm_rank.txt)

**Comment by wenbostar** [comment]
It looks like the difference is due to the setting of tol. The web version is 10 ppm while your command line is using 20 ppm. Could you use 10 ppm to see what you can get?

**Comment by XiaofengxBjmu** [comment]
Thank a lot! I have another question.
I read the issue https://github.com/bzhanglab/PepQuery/issues/34, I found a lot of spectra of TMT labeled MS, that the ten reporter ions intensity very close like following pic. How can I map these spectra to individual samples? 
<img width="419" alt="截屏2022-03-02 下午9 29 58" src="https://user-images.githubusercontent.com/75332489/156415167-cabc4649-1edf-4f83-9145-1d463b6a1f6f.png">

**Comment by XiaofengxBjmu** [comment]
In addition, modification localization is a common problem of the MS database searching, will our results from pepquery also have the problem of inaccurate PTM position? Is there any way to solve this? Thanks a lot!

**Comment by wenbostar** [comment]
> In addition, modification localization is a common problem of the MS database searching, will our results from pepquery also have the problem of inaccurate PTM position? Is there any way to solve this? Thanks a lot!

For each peptide sequence which has a PTM such as the case as shown below, we consider all the possible combinations of PTM and score these different peptide forms against the same spectrum and report the peptide form with the highest score (rank=1) in the output file.
AAAAAAAS(phos)ASASK
AAAAAAASAS(phos)ASK
AAAAAAASASAS(phos)K

**Comment by wenbostar** [comment]
> I read the issue https://github.com/bzhanglab/PepQuery/issues/34, I found a lot of spectra of TMT labeled MS, that the ten reporter ions intensity very close like following pic. How can I map these spectra to individual samples?

It's probably easier to explain this through a Zoom meeting. If you can send me your email, I can set up a Zoom meeting to explain how to map samples.

**Comment by XiaofengxBjmu** [comment]
Thanks! My email is xiaofengx@pku.edu.cn and I'm in Beijing.

**Comment by wenbostar** [comment]
The issue has been solved through Zoom meeting.
