### ISSUE TITLE
clarification of output files

### ISSUE THREAD

**Issue by Seb-Leb** [bzhanglab/PepQuery#4]
The documentation clearly describes some of the files produced by pepquery following the search of a peptide in an mgf dataset. However, it also produces a few files for which I could not find a description in the documentation. For example, the files psm.txt and detail.txt.
Could you also indicate what the absence of the ptm_detail.txt file means? I often get a ptm.txt file without a detail_ptm.txt file.
I run pepquery using peptide search with unrestricted modification and our custom database of reference proteins.
Thank you

**Comment by wenbostar** [comment]
In general, the final novel peptide validation results are included in the **psm_rank.txt** file. Other txt format files are intermediate files that you can ignore. 

If file ptm.txt is present without detail_ptm.txt, it means that there is no better match found in the unrestricted modification searching step.

**Comment by Seb-Leb** [comment]
great, thank you!
