### ISSUE TITLE
Methionine oxidation and Phenylalanine

### ISSUE THREAD

**Issue by apataskar** [bzhanglab/PepQuery#40]
Hi, I am trying to detect a mutant protein that has W->F or W->M substitution. Now, I want to detect both of them using PEPQUERY and see which one is there in cancer proteomes (CPTAC). But, M-oxidation has the same mass as F. I wonder how does PEPQUERY handle this sameness in mass. When I detect W->F, I want to control that with W-> Moxi as well to be 100% sure it is W->F. Can PEPQUERY be used for this purpose?

Looking forward to hear from you.

Thank you :)

Abhijeet Pataskar

**Comment by wenbostar** [comment]
This depends on how close their masses are and the mass tolerance used for matching. Could you provide example peptides  that you want to be distinguished?

**Comment by wenbostar** [comment]
@Abhijeet, please reopen this issue if you still have questions about this topic.
