### ISSUE TITLE
Cannot find sample information in TMT data

### ISSUE THREAD

**Issue by lizhenli8888** [bzhanglab/PepQuery#42]
It is wonderful that both online and standalone version of PepQuery can search TMT datasets. However, it occurred to me that PepQuery did not provide the info regarding which sample the results are matched to.
It seems that PepQuery did not provide TMT tag or reporter iron information in the output， and displayed the results based on TMT fractions. Is it possible to obtained the sample information for the peptide in the output? For example，I searched the peptide with GTEx_32_Tissues dataset, the peptide was found with spectrum_title named “Instrument1_sample01_121115_Fr01:17660:2”，but I could not exactly know it come from which GTEx Tissue.

**Comment by wenbostar** [comment]
This information can be easily found based on this table: https://ftp.pride.ebi.ac.uk/pride/data/archive/2020/11/PXD016999/ModifiedSampleInfo_v2.xlsx and the spectrum_title or spectrum in the output table.

Below please find an example:
The column **spectrum** or **spectrum_title** contains raw MS/MS file (SecondInstrument_Sample13_S2R22_060616_Fr08) which is the first part of the string
<img width="396" alt="image" src="https://user-images.githubusercontent.com/5302110/186191626-6b1113ea-94fb-4bd4-be81-43f9ba83db08.png">. 

From the table raw file-sample mapping table "https://ftp.pride.ebi.ac.uk/pride/data/archive/2020/11/PXD016999/ModifiedSampleInfo_v2.xlsx", you can find the samples for this spectrum **SecondInstrument_Sample13**_S2R22_060616_Fr08:

<img width="903" alt="image" src="https://user-images.githubusercontent.com/5302110/186193121-512217ce-e3f8-4c80-ba4a-ec1ca126ec15.png">

**Comment by lizhenli8888** [comment]
Thank you very much for your kind reply. As the example you make “SecondInstrument_Sample13_S2R22_060616_Fr08”, the spectrum was one of the fractions of SecondInstrument_Sample13. Just as the table shows, “SecondInstrument_Sample13” was a mixture from seven tissues (colon sigmoid, skin, testis, artery coronary, muscle skeletal, thyroid and uterus). TMT tag info in the fourth column of the table is necessary for us to further determine which one of the seven tissues the peptide is matched to. Can I find this information in the output?

**Comment by wenbostar** [comment]
PepQuery exports matched spectra in MGF format (psm_rank.mgf) in which you can find reporter ion information. You could use this to match with sample annotation.

**Comment by wenbostar** [comment]
Please reopen this issue if you still have any question about it.

**Comment by wenbostar** [comment]
Please reopen this issue if you still have any question about it.
