### ISSUE TITLE
Are tags still supported or needed in PepQuery2

### ISSUE THREAD

**Issue by jj-umn** [bzhanglab/PepQuery#43]
We have followed the procedure in: http://pepquery.org/data/PepQuery_for_immunopeptidomics_data.pdf for evaluating potential neoantigens using no-enzyme.  
PepQuery2 does not have option: -tag
Does the the index function in PepQuery2 replace the utility of the tags file?

**Comment by wenbostar** [comment]
The new version no longer needs tag file.

**Comment by jj-umn** [comment]
Thanks for the information.
