### ISSUE TITLE
Enzyme used for protein digestion?

### ISSUE THREAD

**Issue by PMadupe** [bzhanglab/PepQuery#44]
Hi, in the standalone version what does it mean for the the option for -e 0:Non enzyme, does it mean its pepquery its going to be looking for whole proteins or its an unspecified search?

I work with ancient proteins and I don't digest as they are heavily degraded any way, thus I do unspecific searches rather than specific ones or whole protein searches.

**Comment by wenbostar** [comment]
It means an unspecified digestion.

**Comment by wenbostar** [comment]
Please reopen this issue if you still have questions about this.
