### ISSUE TITLE
PepQuery2 Testing- discrepancy in version 1 and 2

### ISSUE THREAD

**Issue by subinamehta** [bzhanglab/PepQuery#45]
@wenbostar and @bingzhang16 
We have been testing the implementation of PepQuery2 in Galaxy and we have some results shared here.

In particular, PepQuery2 seems to generate less number of valid peptides as compared to the earlier version. 

 Tools	        |PSMs|Valid-PSMs|Confident Peptides
PepQuery1	|692|55|38
PepQuery2	|488|32|21

Please see a history that has the inputs (Datasets#1-3), and outputs from PepQuery1 (Datasets#4-7) and PepQuery2 (Datasets#8-16). 

(https://usegalaxy.eu/u/pratikjagtap/h/pepquery2-test)

We were interested to know if the scoring method in PepQuery2 has been updated to make it more stringent and whether there have been any changes to the amino acid substitutions and PTM scoring.
[PSM Rank Comparison.xls](https://github.com/bzhanglab/PepQuery/files/9921506/PSM.Rank.Comparison.xls)

**Comment by wenbostar** [comment]
Could you send me the command line used in running PepQuery 1? I can find the command line for PepQuery2 from the history record at https://usegalaxy.eu/u/pratikjagtap/h/pepquery2-test.

**Comment by subinamehta** [comment]
Sorry to reply so late! Here is the log file- 

Tool Standard Output | 2022-02-24 09:01:35 [ INFO] Start analysis 2022-02-24 09:01:35 [DEBUG] -ms Galaxy6-__ob__09082021_Fusion_COVID_SWAB_2021_R-S97.mgf__cb__.mgf -db Galaxy4-__ob__Galaxy11-__ob__Human_UniProt_SARS-Cov-2_cRAP___cb__.fasta__cb__.fa -pep /panfs/roc/galaxy/PRODUCTION/database/files/001/412/dataset_1412291.dat -indexType 2 -fixMod 6 -varMod 117 -maxVar 3 -um -aa -tol 10 -tolu ppm -itol 0.05 -e 1 -fragmentMethod 1 -m 1 -maxCharge 3 -minCharge 2 -minPeaks 10 -minScore 12 -maxLength 45 -n 1000 -o pepquery_output ############################################# PepQuery parameter: Fixed modification: 6 = Carbamidomethylation of C Variable modification: 117 = Oxidation of M Max allowed variable modification: 3 Add AA substitution: true Enzyme: 1 Max Missed cleavages: 2 Precursor mass tolerance: 10.0 Precursor ion mass tolerance unit: ppm Fragment ion mass tolerance: 0.05 Fragment ion mass tolerance unit: Da Scoring algorithm: 1 = Hyperscore Min score: 10.0 Min peaks: 10 Min peptide length: 7 Max peptide length: 45 Min peptide mass: 500.0 Max peptide mass: 10000.0 Random peptide number: 1000 CPU: 24
-- | --

**Comment by wenbostar** [comment]
@subinamehta , please reopen this issue if you still have any questions about it.
