### ISSUE TITLE
results differences between peppery 1 and peppery 2

### ISSUE THREAD

**Issue by rboulos** [bzhanglab/PepQuery#46]
We have been running pepquery 1 and 2 with exactly the same parameters and noticed difference between the obtained results. Some spectra appeared confident with version 1 and are no longer confident in version 2. We noticed that this is due to the n_ptm value that is getting larger numbers in version 2. We understand from reading issue #45 this could be due to the updates in version 2 considering multiple variable modifications in the unrestricted modifications searching step vs only 1 in version 1. This means that more peptides are considered and this might increase this n_ptm number. 
Do you consider a very stringent cutoff is needed when working with novel sequences or do you think we can set n_ptm to be smaller than a certain value (such as 3 or 5 maybe) to have a less stringent cutoff? In that case do you have any recommendations on the threshold to use?

**Comment by wenbostar** [comment]
It may not be an appropriate filtering based on a fixed value of n_ptm. One way you might want to try is to filter with "[mod_delta_score](http://pepquery.org/document.html#saoutput)" (such as mod_delta_score <=2) from the [psm_rank.txt](http://pepquery.org/document.html#saoutput) file combined with [delta RT](https://www.nature.com/articles/s41467-020-15456-w) for the original matches.

**Comment by wenbostar** [comment]
Please reopen this issue if you still have questions.
