### ISSUE TITLE
Access to the website

### ISSUE THREAD

**Issue by mirjam514** [bzhanglab/PepQuery#47]
Hello, 

I would like to use the PepQuery website, but whenever I click on the link, I get an error message ("aws2.zhang-lab.org took too long to respond.") This problem occurs on all computers and browsers we have tried. 
Do you have any idea what the problem might be?
Thank you for your help!

**Comment by zhiaos** [comment]
can you let me know which link are you trying to access?  I have no problem accessing pepquery2.pepquery.org

**Comment by mirjam514** [comment]
The same one, http://pepquery2.pepquery.org/. The http://www.pepquery.org/ works fine, but https://aws2.zhang-lab.org/ doesn't seem to work for us, all it shows is Hello world. We assume that the problem might be related to our location (Hungary).

**Comment by zhiaos** [comment]
is it possible your local firewall blocking access to port 3838 on remote server?   Since pepquery is an R shiny app, it uses the default 3838 port.

**Comment by wenbostar** [comment]
>  Hello,
> I would like to use the PepQuery website, but whenever I click on the link, I get an error message ("aws2.zhang-lab.org took too long to respond.") This problem occurs on all computers and browsers we have tried.
Do you have any idea what the problem might be?
Thank you for your help!

This could happen when another user is using the web server. The [web server](http://pepquery2.pepquery.org/) only allows to submit one job at a time to make full use of the computer resource to speed up the search. When a job is running, users have to wait the job to be finished to view the [main page](http://pepquery2.pepquery.org/) or submit a new job. 

You can use the [standalone version](http://pepquery.org/download.html) to search all the datasets available on the [web server](http://pepquery2.pepquery.org/). That means any search performed through the [web server](http://pepquery2.pepquery.org/) can be done with the [standalone version](http://pepquery.org/download.html) on a computer with internet connection. You could find some examples at http://pepquery.org/document.html#saexample.

**Comment by mirjam514** [comment]
Thank you very much, it is working now!
