### ISSUE TITLE
How to search multiple novel proteins?

### ISSUE THREAD

**Issue by mt1022** [bzhanglab/PepQuery#51]
Dear PepQuery2 developers,

Thanks for developing this powerful search engine. In your recent paper, PepQuery2 was used to query hundreds of nuORFs against proteomic datasets. We has also annotated thousands of novel ORFs recently and we would like to search them for MS evidence. I have reviewed the documentation page and I see that it is only possible to search a single novel protein at a time. I would be grateful if you could let me know if there is a way to search multiple novel proteins with PepQuery2.

Thank you for your time and consideration.

Sincerely,
Hong

**Comment by wenbostar** [comment]
For each search, only one protein is supported. But if you have a cluster, you could submit multiple jobs with each job searhing for one protein.

**Comment by mt1022** [comment]
Thanks for the explanation. We do have a cluster, but the internet connection to aws is restricted. We'll try and see what else we can do.

**Comment by wenbostar** [comment]
You could also try to download the MS/MS raw data files and [build local index files](http://pepquery.org/document.html#index) for searching.

**Comment by wenbostar** [comment]
The MS/MS files (in .raw or mzML format) for all the datasets available in [PepQueryDB](http://pepquery2.pepquery.org/) can be accessed based on the links provided at http://pepquery2.pepquery.org/.

**Comment by mt1022** [comment]
This is helpful! We will download raw files and try local search.
