### ISSUE TITLE
PepQuery and DIA files? - Searching in Galaxy

### ISSUE THREAD

**Issue by prao123** [bzhanglab/PepQuery#55]
Hello, 
I am using PepQuery2 in Galaxy for analysis of novel peptide identification. The spectral files is collected in DIA mode using FAIMS. PepQuery does not result in any output (0 peptides listed in the psm_rank.txt file). The peptide list was searched against both mgf or mzML spectral files. DDA datasets work fine. Is PQ2 incompatible with DIA datasets?
Thanks

**Comment by wenbostar** [comment]
Sorry, PepQuery2 doesn't support DIA dataset directly. But you may want to try to convert your DIA spectra to DDA-like spectra using DIA-Umpire and then search the DIA-Umpire converted MGF using PepQuery2.

**Comment by prao123** [comment]
Got it. Thanks for the DIA-Umpire suggestion.
