### ISSUE TITLE
ERROR: There is no file found in this dataset

### ISSUE THREAD

**Issue by sarinita** [bzhanglab/PepQuery#56]
Hi,
I am getting following error when using public proteome databases (from PRIDE or massIVE): "There is no file found in this dataset". I tried various datasets with mgf or mzML-files (e.g MSV000081607), but none are working. A few weeks ago, it was still functioning (the same line that previously worked gives now an error).
Could you help me here?

Thanks a lot in advance!

**Comment by wenbostar** [comment]
Could you please post your PepQuery command line here?

**Comment by sarinita** [comment]
sure, here it is: 
java -jar pepquery-2.0.2/pepquery-2.0.2.jar -b MSV000089856:mzML -db gencode:human -o motscMSV000089856/ -i MRWQEMGYIFYPRKLR -t protein -fast
or
java -jar pepquery-2.0.2/pepquery-2.0.2.jar -b MSV000081563:mzML -db gencode:human -o output/ -i MRWQEMGYIFYPRKLR -t protein -fast
I also tried not to specify the files to be searched:
java -jar pepquery-2.0.2/pepquery-2.0.2.jar -b MSV000081563 -db gencode:human -o output/ -i MRWQEMGYIFYPRKLR -t protein -fast

but I always get the same error for files from public databases
For the pepquery datasets, everything works fine.

**Comment by optiprime8** [comment]
Hi,

I am also getting this "There is no file found in this dataset" error when using PRIDE datasets.
