### ISSUE TITLE
Semi tryptic searches

### ISSUE THREAD

**Issue by colin986** [bzhanglab/PepQuery#57]
Hello, 

I was wondering if it was possible to select a semi tryptic digestion option for the standalone version of PepQuery?

Thanks,
Colin

**Comment by wenbostar** [comment]
Hi Colin,

I'm sorry that the current version doesn't support semi tryptic digestion. But this shouldn't be difficult to add.

**Comment by colin986** [comment]
Thanks @wenbostar! 

So are you saying that I should perform my own semi-tryptic digest and pass in a list of peptides? 

Best,
Colin

**Comment by wenbostar** [comment]
Could you give a bit more details about why you wanted to perform a semi-tryptic digestion in PepQuery search?

**Comment by colin986** [comment]
No problem - I have a list of approx 3k novel microproteins. I digest them in silico with semi tryptic specificity (which is generally what have others have done for traditional database searches) outside pepquery then input the list of peptides. 

This approach works very well at the moment, and I have a very reasonable number of PSMs designated as confident for my samples. 

I then map the PSMs back to the protein. 

My question related to known proteome, and if there was a way to perform a semi-tryptic digestion for that. I realise that the computation time would increase significantly and maybe it doesn’t need to be done all? 

Ps I actually perform two searches, one with ox on m as a variable mod. And then for the second I take the first peptide from each protein and search with ox on M and peptide n-term actylation, which is protein n-term acetlyation. I merge the 2 results at the end

**Comment by wenbostar** [comment]
Could you email me? I can send you a version which supports semi-digestion in the next few days.

**Comment by colin986** [comment]
Sure! What’s your email address? 
thanks

**Comment by wenbostar** [comment]
Could you tell me your gmail if you have one so that I can send you the version for testing through google drive?

**Comment by colin986** [comment]
Clarke.m.colin@gmail.com

thanks!

**Comment by wenbostar** [comment]
I have sent you a new version.
