### ISSUE TITLE
Sample info not showing up in the web application

### ISSUE THREAD

**Issue by emilyhmwong-vir** [bzhanglab/PepQuery#60]
Hi,

I was using the web application to search for a novel protein. I had selected a dataset from CPTAC. 3 peptides were identified in confidence. However, the sample information tab was empty, after I clicked on one of the peptides in the "Identification Result" panel.

Could we query the CPTAC data using the standalone tool?

Best,
Emily

**Comment by wenbostar** [comment]
Sorry, we haven't prepared sample information for many of the datasets in the web server. For CPTAC datasets, you could find the sample information by querying the spectrum file names in [PDC](https://proteomic.datacommons.cancer.gov/pdc/).

**Comment by wenbostar** [comment]
> Could we query the CPTAC data using the standalone tool?

Yes.

**Comment by emilyhmwong-vir** [comment]
Thanks Bo!
