### ISSUE TITLE
Could not resolve dependencies for project Proteomics:pepquery:jar:2.0.5

### ISSUE THREAD

**Issue by adajani** [bzhanglab/PepQuery#62]
I got this error when I tried to build using **mvn clean compile**

The following artifacts could not be resolved: JFASTA:JFASTA:jar:2.2.0 (absent): JFASTA:JFASTA:jar:2.2.0 was not found in https://genesis.UGent.be/maven2 during a previous attempt

**Comment by wenbostar** [comment]
This might be due to network issue. Could you please try it again?
