### ISSUE TITLE
Question: finding evidence(s) of a peptide translated from an "Upstream Open Reading Frame (uORF)"

### ISSUE THREAD

**Issue by lindenb** [bzhanglab/PepQuery#63]
(cross posted : https://www.biostars.org/p/9595035/ )

Hi the PepQuery team,
I work as a bioinformatician in the field of genomics and I don't know anything about mass-spectrometry.

I'm interested with short peptides generated by uORF:

> ( https://en.wikipedia.org/wiki/Upstream_open_reading_frame) An upstream open reading frame (uORF) is an open reading frame (ORF) within the 5' untranslated region (5'UTR) of an mRNA. uORFs can regulate eukaryotic gene expression.Translation of the uORF typically inhibits downstream expression of the primary ORF.

for example: a short peptide `MEQSRFLTQDLMVFRDCRH` is generated by a uORF of a gene on chr10:

```
>>> 279332
$1                   Taxon : Homo sapiens
$2                Assembly : hg38
$3                     Chr : chr10
$22              uORFstart : 35188214
$23                uORFend : 35188274
$34           uORFaminoSeq : MEQSRFLTQDLMVFRDCRH*
<<< 279332
```

is it possible to use your database to check if such peptide was found  in-vivo ? If so , what would be the best set of parameters to find and to validate the existence of such peptide ?

Thank your for your help;

PL.

**Comment by wenbostar** [comment]
You can search your uORF-derived peptides against all the proteomics datasets in PepQuery through the web server or the standalone version. You can directly use the predefined parameter settings for each individual datasets that should work well.
