### ISSUE TITLE
Quantification of the novel peptide 

### ISSUE THREAD

**Issue by anuC** [bzhanglab/PepQuery#66]
Hi,

I am using standalone version for novel peptide identification/validation and I could identify the presence the novel peptide with 'yes' in the 'confident' column (I am with no experience in MS analysis). Now, I wonder whether the PepQery can provide any information about the quantity of the specific novel peptide in the MS sample or is there a way I can quantify the novel peptide from MS dataset.

Any help would be highly appreciated

Thanks in advance
Anu

**Comment by wenbostar** [comment]
Hi Anu, unfortunately not. I'd like to recommemd to use [FragPipe pipeline for quantification](https://github.com/bzhanglab/PepQuery/issues/61). In brief, you could first validate your novel peptides using PepQuery and then create a new database by including both the novel peptides passed PepQuery validation and all reference proteins for FragPipe quantification.

**Comment by anuC** [comment]
Hi Bo, Thanks for the information.
