### ISSUE TITLE
Trypsin digestion and unique peptide identification

### ISSUE THREAD

**Issue by anuC** [bzhanglab/PepQuery#69]
Hi,

I am using standalone version of PepQuery for protein identification.  After trypsin digestion, PepQuery identified below peptides as unique. However, it seems like trypsin digestion with Pepquery is incomplete, as I could note that some peptides are missed. The following command was used with PepQuery

`java -Xmx30G -jar pepquery-2.0.2/pepquery-2.0.2.jar -b CPTAC -db GRCh38_latest_protein.fasta -hc -s 1 -m 1 -o pepquery_out/ -i MIKFSWSQTMRTEWRKARLSLEQLSHTPGSRTPRLFCS -t protein -fast`

PepQuery listed following peptides as unique

> ^[[m^[[32m2024-08-07 10:59:25 [INFO ] main.java.pg.PepMapping[init:88] - Indexing took 0.483184339 seconds and consumes 246.462 MB
^[[m^[[32m2024-08-07 10:59:25 [INFO ] main.java.pg.InputProcessor[run:178] - FSWSQTMR is not exist in the reference protein database.
^[[m^[[32m2024-08-07 10:59:25 [INFO ] main.java.pg.InputProcessor[run:178] - MIKFSWSQTMR is not exist in the reference protein database.
^[[m^[[32m2024-08-07 10:59:25 [INFO ] main.java.pg.InputProcessor[run:178] - FSWSQTMRTEWR is not exist in the reference protein database.
^[[m^[[32m2024-08-07 10:59:25 [INFO ] main.java.pg.InputProcessor[run:178] - LSLEQLSHTPGSR is not exist in the reference protein database.
^[[m^[[32m2024-08-07 10:59:25 [INFO ] main.java.pg.InputProcessor[run:178] - **ARLSLEQLSHTPGSR** is not exist in the reference protein database.
^[[m^[[32m2024-08-07 10:59:25 [INFO ] main.java.pg.InputProcessor[run:178] - LSLEQLSHTPGSRTPR is not exist in the reference protein database.
^[[m^[[32m2024-08-07 10:59:25 [INFO ] main.java.pg.InputProcessor[run:178] - TPRLFCS is not exist in the reference protein database.                                                                                                            ^[[m^[[32m2024-08-07 10:59:25 [INFO ] main.java.pg.PeptideSearchMT[search:395] - Total target peptides:7, unique peptides:7, shared peptides:0

However,I could see that a peptide with sequence - KARLSLEQLSHTPGSR, is missing in the above list. As the peptide ARLSLEQLSHTPGSR is listed as the unique peptide, I wonder why PepQuery missed a very similar peptide KARLSLEQLSHTPGSR being listed as the unique one?

**Comment by wenbostar** [comment]
Peptide "**K**A**R**LSLEQLSHTPGSR" has two missed cleavage sites but the parameter setting only allows a maximum of one missed cleavage site.

**Comment by wenbostar** [comment]
If you really want to include that peptide, you could add this parameter "[-c 2](http://pepquery.org/document.html#saparameter)" by set the allowed maximum missed cleavage site to 2. But this will slow down the search.

**Comment by anuC** [comment]
Thank you the prompt reply.
