### ISSUE TITLE
Invalid peptide problem

### ISSUE THREAD

**Issue by olson-t** [bzhanglab/PepQuery#8]
I ran the stand-alone version of PepQuery on Linux and used this command:
java -jar pepquery.jar -pep peptide.txt -db custom1.fasta -ms HLA-1.mgf -varMod 21,117 -maxVar 5 -tol 20 -tolu ppm -e 0 -cpu 4 -minLength 8 -maxLength 15
And it said all the peptides on the file were invalid.

I then added the peptide used in the demonstration of the web application in the document, removing the ending R to simulate the peptides I have. PepQuery only recognised that peptide as valid. And even a random peptide is treated as valid (although it did not match the MGF file well.

How could I solve the issue and what would be the reason for it? Thanks

**Comment by wenbostar** [comment]
The output message of "invalid" means that the query peptide can be exactly matched to your reference database (custom1.fasta) so it's not a potential novel peptide and will not be searched by PepQuery against your input MS/MS data. The message "valid" only means that the input query peptide can not be exactly matched to any protein sequences in your input reference database (-db).

**Comment by wenbostar** [comment]
Are you trying to search novel peptides in HLA-binding peptide enriched peptidomics data? The current version of PepQuery is not optimized for this type of searching (no-enzyme digestion) which has extremely large search space. It may be very slow and use a lot of memory.

**Comment by olson-t** [comment]
I see, thanks!

**Comment by wenbostar** [comment]
Recently we updated PepQuery to support peptidomics data.  If you are still interested in this function, please find a tutorial at http://pepquery.org/document.html#immunopeptidomics and please let me know if you have any questions about this function.
